# Temporal Motif Feature Extraction for Ethereum Fraud Detection

## 1. Import Libraries and Load Data

In [1]:
import polars as pl
from pathlib import Path
from collections import defaultdict
from bisect import bisect_left, bisect_right
import pandas as pd

In [2]:
# Load community definitions, labeled fraud data, and transaction logs
infomap = pd.read_csv(Path("infomap_communities.csv"))  # Cluster allocations computed by the Infomap algorithm
fraud = pd.read_csv(Path("all_detected_fraud_accounts.csv"))  # Verified malicious account registry (ground-truth dataset)
df = pl.read_csv("eth_tx_last4days_clean.csv")  # Main collection of parsed Ethereum transaction ledgers

## 2. Data Preprocessing

Cast the columns to their proper formats, standardize string hashes, extract native numeric unix timestamps, convert raw transaction sizes from Wei to Ether, and strictly sort chronologically to enable windowed streaming operations.

In [3]:
events = (
    df
    .select([
        pl.col("hash"),
        pl.col("from_address").str.to_lowercase().alias("source"),
        pl.col("to_address").str.to_lowercase().alias("target"),
        pl.col("value").alias("value_wei"),
        pl.col("block_timestamp")
    ])
    .with_columns([
        pl.col("target").fill_null("__contract_creation__"),
        (
            pl.col("block_timestamp")
            .str.to_datetime(format="%Y-%m-%d %H:%M:%S%z")
            # Construct standard temporal Unix timestamps (seconds)
            .dt.timestamp("ms") // 1000
        ).alias("timestamp"),
        (
            pl.col("value_wei").cast(pl.Float64, strict=False) / 1_000_000_000_000_000_000
        # Convert the numeric value to standard Ether scales
        ).alias("value_eth")
    ])
    .select([
        "hash",
        "source",
        "target",
        "timestamp",
        "block_timestamp",
        "value_wei",
        "value_eth"
    ])
    # Enforce absolute sequential ordering by transaction time
    .sort("timestamp")
)

In [4]:
# Verify shape, schema, and look for any remaining missing values
print(events.shape)
print(events.schema)

# Run extensive structural data assertions and print descriptive aggregations
events.select([
    pl.col("timestamp").null_count().alias("missing_timestamp"),
    pl.col("source").null_count().alias("missing_source"),
    pl.col("target").null_count().alias("missing_target"),
    pl.col("value_wei").null_count().alias("missing_value_wei"),
    pl.col("value_eth").null_count().alias("missing_value_eth"),
    pl.col("timestamp").min().alias("min_timestamp"),
    pl.col("timestamp").max().alias("max_timestamp"),
    pl.col("block_timestamp").first().alias("first_block_timestamp"),
    pl.col("block_timestamp").last().alias("last_block_timestamp"),
    pl.col("value_eth").min().alias("min_value_eth"),
    pl.col("value_eth").max().alias("max_value_eth"),
    pl.col("value_eth").mean().alias("mean_value_eth")
])

(4290480, 7)
Schema([('hash', String), ('source', String), ('target', String), ('timestamp', Int64), ('block_timestamp', String), ('value_wei', Float64), ('value_eth', Float64)])

shape: (1, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ missing_t ┆ missing_s ┆ missing_t ┆ missing_v ┆ … ┆ last_bloc ┆ min_value ┆ max_value ┆ mean_val │
│ imestamp  ┆ ource     ┆ arget     ┆ alue_wei  ┆   ┆ k_timesta ┆ _eth      ┆ _eth      ┆ ue_eth   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ mp        ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 2025-11-1 ┆ 0.0       ┆ 39448.75  ┆ 0.688368 │
│           ┆           ┆           ┆           ┆   ┆ 0 16:54:3 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 5+00:00   ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 3. Community Selection

Aggregate duplicated illicit accounts to construct flat records with unique node addresses, concatenate multi-type behavior labels, and map them explicitly onto Infomap network indices to discover high-density anomaly targets.

In [5]:
# Deduplicate fraud data and combine multi-type labels per address
fraud_clean = (
    fraud
    .groupby("address", as_index=False)
    .agg({
        # Unify label properties safely
        "detected_type": lambda x: ";".join(sorted(set(x.dropna().astype(str)))),
        # Select the default first mapping node
        "node_id": "first"
    })
)

# Explicit class definition assignment for targets
fraud_clean["label"] = "fraud"

print("Fraud clean shape:", fraud_clean.shape)
display(fraud_clean.head())

Fraud clean shape: (4351, 4)

                                      address detected_type  node_id  label
0  0x0000000000000000000000000000000000000000      phishing        1  fraud
1  0x0000000000000000000000000000000000001002      phishing        4  fraud
2  0x00000000000000447e69651d841bd8d104bed493      phishing        8  fraud
3  0x000000000000f10286d9c1c5d4635a25070572b6      phishing       37  fraud
4  0x0000000000771a79d0fc7f3b7fe270eb4498f20b      phishing       71  fraud

In [6]:
# Left merge structural node partitions with clean fraud classifications
nodes = infomap.merge(
    fraud_clean[["address", "label", "detected_type"]],
    on="address",
    how="left"
)

# Populate missing missing labels explicitly as standard 'normal' profiles
nodes["label"] = nodes["label"].fillna("normal")
nodes["detected_type"] = nodes["detected_type"].fillna("normal")

print("Nodes shape:", nodes.shape)

print(nodes["label"].value_counts())

Nodes shape: (1686534, 4)
label
normal    1682526
fraud        4008
Name: count, dtype: int64

In [7]:
# Compute core metrics (total sizes, actual fraud node occurrences, and density indices) for each community cluster
community_stats = (
    nodes
    .groupby("infomap_id")
    .agg(
        n_nodes=("address", "count"),
        n_fraud_nodes=("label", lambda x: (x == "fraud").sum()),
        n_normal_nodes=("label", lambda x: (x == "normal").sum())
    )
    .reset_index()
)

# Calculate ratio percentages and sort by density scale metrics
community_stats["fraud_rate"] = (
    community_stats["n_fraud_nodes"] / community_stats["n_nodes"]
)

community_stats = community_stats.sort_values(
    ["n_fraud_nodes", "n_nodes"],
    ascending=[False, False]
)

display(community_stats.head(20))

       infomap_id  n_nodes  n_fraud_nodes  n_normal_nodes  fraud_rate
845           846     2820            459            2361    0.162766
20             21   265670             57          265613    0.000215
389           390    17500             46           17454    0.002629
241           242     5901             28            5873    0.004745
1139         1140      187             26             161    0.139037
2900         2901      175             26             149    0.148571
277           278     7853             16            7837    0.002037
494           495     5104             16            5088    0.003135
1035         1036      774             14             760    0.018088
246           247     5825             13            5812    0.002232
483           484      281             12             269    0.042705
22338       22339       36             12              24    0.333333
221           222    84785             11           84774    0.000130
316           317     8200             11            8189    0.001341
1134         1135     2485             10            2475    0.004024
781           782     3377              9            3368    0.002665
1619         1620       39              9              30    0.230769
262           263    12047              8           12039    0.000664
130           131     7776              8            7768    0.001029
371           372     6545              8            6537    0.001222

In [8]:
# Isolate verified illicit entities and track distinct crime profiles inside clusters
fraud_nodes = nodes[nodes["label"] == "fraud"].copy()

fraud_type_by_community = (
    fraud_nodes
    .groupby(["infomap_id", "detected_type"])
    .agg(
        n_fraud_type=("address", "count")
    )
    .reset_index()
)

# Sort distributions progressively based on criminal category types
fraud_type_by_community = fraud_type_by_community.sort_values(
    ["detected_type", "n_fraud_type"],
    ascending=[True, False]
)

In [9]:
for fraud_type in fraud_nodes["detected_type"].unique():
    print("=" * 80)
    print("Fraud type:", fraud_type)
    
    temp = (
        fraud_nodes[fraud_nodes["detected_type"] == fraud_type]
        .groupby("infomap_id")
        .agg(
            n_this_type=("address", "count")
        )
        .reset_index()
        .merge(
            community_stats[["infomap_id", "n_nodes", "n_fraud_nodes", "n_normal_nodes", "fraud_rate"]],
            on="infomap_id",
            how="left"
        )
        .sort_values("n_this_type", ascending=False)
    )
    
    display(temp.head(10))

================================================================================
Fraud type: phishing

,infomap_id,n_this_type,n_nodes,n_fraud_nodes,n_normal_nodes,fraud_rate
91,390,45,17500,46,17454,0.002629
4,21,22,265670,57,265613,0.000215
119,495,16,5104,16,5088,0.003135
202,1036,13,774,14,760,0.018088
117,484,12,281,12,269,0.042705
57,247,11,5825,13,5812,0.002232
262,1620,9,39,9,30,0.230769
51,222,8,84785,11,84774,0.000130
21,127,8,542,8,534,0.014760
56,242,7,5901,28,5873,0.004745

================================================================================
Fraud type: mixer

,infomap_id,n_this_type,n_nodes,n_fraud_nodes,n_normal_nodes,fraud_rate
3,21,27,265670,57,265613,0.000215
23,242,17,5901,28,5873,0.004745
31,278,14,7853,16,7837,0.002037
530,22339,10,36,12,24,0.333333
99,782,9,3377,9,3368,0.002665
42,314,8,6028,8,6020,0.001327
13,165,6,12,7,5,0.583333
125,1135,5,2485,10,2475,0.004024
77,573,5,2660,6,2654,0.002256
50,372,5,6545,8,6537,0.001222

================================================================================
Fraud type: wash_trading

,infomap_id,n_this_type,n_nodes,n_fraud_nodes,n_normal_nodes,fraud_rate
68,846,455,2820,459,2361,0.162766
145,2901,26,175,26,149,0.148571
85,1140,26,187,26,161,0.139037
0,21,6,265670,57,265613,0.000215
152,3091,6,107,6,101,0.056075
67,819,5,45,5,40,0.111111
217,7339,4,86,4,82,0.046512
84,1135,4,2485,10,2475,0.004024
356,34557,4,38,4,34,0.105263
16,242,3,5901,28,5873,0.004745

================================================================================
Fraud type: mixer;wash_trading

,infomap_id,n_this_type,n_nodes,n_fraud_nodes,n_normal_nodes,fraud_rate
161,14677,3,57,8,49,0.140351
40,1387,3,101,7,94,0.069307
6,307,3,11440,6,11434,0.000524
0,21,2,265670,57,265613,0.000215
15,507,2,3060,6,3054,0.001961
145,9466,2,58,2,56,0.034483
71,3076,2,171,5,166,0.029240
28,783,2,102,2,100,0.019608
207,55869,2,26,2,24,0.076923
113,5620,1,54,1,53,0.018519

================================================================================
Fraud type: phishing;wash_trading

,infomap_id,n_this_type,n_nodes,n_fraud_nodes,n_normal_nodes,fraud_rate
1,279,3,4540,7,4533,0.001542
0,247,2,5825,13,5812,0.002232
28,17010,1,44,1,43,0.022727
27,16223,1,35,1,34,0.028571
26,15655,1,39,2,37,0.051282
25,10448,1,37,1,36,0.027027
24,9638,1,56,1,55,0.017857
23,9333,1,125,3,122,0.024000
22,9053,1,36,1,35,0.027778
21,8207,1,20,1,19,0.050000

================================================================================
Fraud type: mixer;phishing

,infomap_id,n_this_type,n_nodes,n_fraud_nodes,n_normal_nodes,fraud_rate
0,263,1,12047,8,12039,0.000664
1,294,1,1719,2,1717,0.001163
18,20917,1,10,1,9,0.100000
17,14777,1,13,2,11,0.153846
16,14135,1,9,2,7,0.222222
15,12184,1,99,1,98,0.010101
14,10312,1,21,3,18,0.142857
13,8399,1,163,1,162,0.006135
12,6996,1,133,1,132,0.007519
11,3576,1,243,2,241,0.008230

================================================================================
Fraud type: mixer;phishing;wash_trading

   infomap_id  n_this_type  n_nodes  n_fraud_nodes  n_normal_nodes  fraud_rate
0         291            1     2183              2            2181    0.000916
1         971            1      184              2             182    0.010870
2        5573            1       90              1              89    0.011111
3        8531            1       46              2              44    0.043478

In [10]:
selected_communities = {
    "wash_trading": 846,
    "phishing": 390,
    "mixer": 242
}

selected_node_lists = {}

for name, community_id in selected_communities.items():
    temp = nodes[nodes["infomap_id"] == community_id].copy()
    selected_node_lists[name] = temp
    
    print("=" * 80)
    print(name)
    print("infomap_id:", community_id)
    print("n_nodes:", len(temp))
    print("\nLabel counts:")
    print(temp["label"].value_counts())
    print("\nDetected type counts:")
    print(temp[temp["label"] == "fraud"]["detected_type"].value_counts())
    
    output_name = f"selected_{name}_community_{community_id}_nodes.csv"
    temp.to_csv(output_name, index=False)
    print("\nSaved:", output_name)

================================================================================
wash_trading
infomap_id: 846
n_nodes: 2820

Label counts:
label
normal    2361
fraud      459
Name: count, dtype: int64

Detected type counts:
detected_type
wash_trading          455
phishing                2
mixer;wash_trading      1
mixer                   1
Name: count, dtype: int64

Saved: selected_wash_trading_community_846_nodes.csv
================================================================================
phishing
infomap_id: 390
n_nodes: 17500

Label counts:
label
normal    17454
fraud        46
Name: count, dtype: int64

Detected type counts:
detected_type
phishing    45
mixer        1
Name: count, dtype: int64

Saved: selected_phishing_community_390_nodes.csv
================================================================================
mixer
infomap_id: 242
n_nodes: 5901

Label counts:
label
normal    5873
fraud       28
Name: count, dtype: int64

Detected type counts:
detected_type
mixer                 17
phishing               7
wash_trading           3
mixer;wash_trading     1
Name: count, dtype: int64

Saved: selected_mixer_community_242_nodes.csv


## 4. Temporal Window Selection

Conduct exploratory data analysis using temporal sliding windows across sample interaction pairs to discover empirical delays, evaluate motif frequency variations, and choose the optimal Δ interval.

In [11]:
motif_sample = (
    events
    .filter(pl.col("target") != "__contract_creation__")
    .filter(pl.col("source") != pl.col("target"))
    .select([
        "hash",
        "source",
        "target",
        "timestamp",
        "block_timestamp",
        "value_wei"
    ])
    .sort("timestamp")
)

motif_sample.shape

(4235659, 6)

In [12]:
motif_sample.select([
    pl.col("timestamp").min().alias("min_timestamp"),
    pl.col("timestamp").max().alias("max_timestamp"),
    ((pl.col("timestamp").max() - pl.col("timestamp").min()) / 60).alias("duration_minutes"),
    pl.len().alias("n_events")
])

shape: (1, 4)
┌───────────────┬───────────────┬──────────────────┬──────────┐
│ min_timestamp ┆ max_timestamp ┆ duration_minutes ┆ n_events │
│ ---           ┆ ---           ┆ ---              ┆ ---      │
│ i64           ┆ i64           ┆ f64              ┆ u32      │
╞═══════════════╪═══════════════╪══════════════════╪══════════╡
│ 1762546907    ┆ 1762793675    ┆ 4112.8           ┆ 4235659  │
└───────────────┴───────────────┴──────────────────┴──────────┘

In [13]:
tx_per_minute = (
    motif_sample
    .with_columns((pl.col("timestamp") // 60).alias("minute_bin"))
    .group_by("minute_bin")
    .agg(pl.len().alias("n_tx"))
    .sort("minute_bin")
)

tx_per_minute.select([
    pl.col("n_tx").min().alias("min_tx_per_minute"),
    pl.col("n_tx").median().alias("median_tx_per_minute"),
    pl.col("n_tx").max().alias("max_tx_per_minute")
])

shape: (1, 3)
┌───────────────────┬──────────────────────┬───────────────────┐
│ min_tx_per_minute ┆ median_tx_per_minute ┆ max_tx_per_minute │
│ ---               ┆ ---                  ┆ ---               │
│ u32               ┆ f64                  ┆ u32               │
╞═══════════════════╪══════════════════════╪═══════════════════╡
│ 168               ┆ 1024.0               ┆ 1984              │
└───────────────────┴──────────────────────┴───────────────────┘

### 4.1 Reciprocity Window Sensitivity Analysis

Evaluate the occurrence rate, total address involvement, and financial weight distribution of rapid bidirectional reciprocity motifs (A→B followed by B→A) across varying sliding window sizes (Δ).

In [14]:
# Establish a broad exploratory evaluation horizon (24 hours in seconds)
max_delta = 24 * 60 * 60

# Extract forward-directed sender properties and sort sequentially
left = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_1"),
        pl.col("source").alias("a"),
        pl.col("target").alias("b"),
        pl.col("timestamp").alias("t1"),
        pl.col("value_wei").alias("value_1")
    ])
    .sort(["a", "b", "t1"])
)

# Extract inverse-directed structural lines to locate back-and-forth interactions
right = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_2"),
        pl.col("target").alias("a"),
        pl.col("source").alias("b"),
        pl.col("timestamp").alias("t2"),
        pl.col("value_wei").alias("value_2")
    ])
    .sort(["a", "b", "t2"])
)

# Identify potential reciprocity structures within the maximum observation window
reciprocity_candidates = (
    left
    .join_asof(
        right,
        left_on="t1",
        right_on="t2",
        by=["a", "b"],
        strategy="forward",
        tolerance=max_delta
    )
    .filter(pl.col("t2").is_not_null())
    .filter(pl.col("t2") > pl.col("t1"))
    .with_columns((pl.col("t2") - pl.col("t1")).alias("delay_seconds"))
)

reciprocity_candidates.head()

/var/folders/3k/bctm07x95zjcttz_6djk0y180000gn/T/ipykernel_20074/2922947204.py:32: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  left

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash_1    ┆ a         ┆ b         ┆ t1        ┆ … ┆ hash_2    ┆ t2        ┆ value_2   ┆ delay_se │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ conds    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ i64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0x5b72838 ┆ 0x000019c ┆ 0xe596247 ┆ 176277371 ┆ … ┆ 0xa2a14c6 ┆ 176277431 ┆ 3.0000e16 ┆ 600      │
│ d2aefa5e4 ┆ 77100b0cb ┆ 9d187a214 ┆ 9         ┆   ┆ ce288ce62 ┆ 9         ┆           ┆          │
│ 8c9f4daf3 ┆ 544fe48a7 ┆ bd81df5f4 ┆           ┆   ┆ dbc01705c ┆           ┆           ┆          │
│ 93b…      ┆ bde…      ┆ 3b0…      ┆           ┆   ┆ b62…      ┆           ┆           ┆          │
│ 0xf966f1e ┆ 0x0003b5a ┆ 0xa9ac43f ┆ 176256665 ┆ … ┆ 0x3a21281 ┆ 176257121 ┆ 4.5188e20 ┆ 4560     │
│ d42a447a2 ┆ a5e30e97f ┆ 5b5e38155 ┆ 9         ┆   ┆ 9752b704d ┆ 9         ┆           ┆          │
│ d348a6236 ┆ cc596bb5d ┆ a288d1a01 ┆           ┆   ┆ a8908b21f ┆           ┆           ┆          │
│ 370…      ┆ 0f3…      ┆ d2c…      ┆           ┆   ┆ 95f…      ┆           ┆           ┆          │
│ 0x846be63 ┆ 0x0003b5a ┆ 0xa9ac43f ┆ 176261108 ┆ … ┆ 0xd5c9083 ┆ 176261326 ┆ 4.8867e20 ┆ 2184     │
│ 29ad8239d ┆ a5e30e97f ┆ 5b5e38155 ┆ 3         ┆   ┆ 8fbbec5e9 ┆ 7         ┆           ┆          │
│ 58dd1cf70 ┆ cc596bb5d ┆ a288d1a01 ┆           ┆   ┆ 0a5ce83ae ┆           ┆           ┆          │
│ 709…      ┆ 0f3…      ┆ d2c…      ┆           ┆   ┆ 451…      ┆           ┆           ┆          │
│ 0x23678c8 ┆ 0x0003b5a ┆ 0xa9ac43f ┆ 176261363 ┆ … ┆ 0x1712457 ┆ 176265298 ┆ 6.1506e20 ┆ 39348    │
│ b7ebe5070 ┆ a5e30e97f ┆ 5b5e38155 ┆ 9         ┆   ┆ 5afeedf9f ┆ 7         ┆           ┆          │
│ 5d0481127 ┆ cc596bb5d ┆ a288d1a01 ┆           ┆   ┆ 525dd0d49 ┆           ┆           ┆          │
│ 8f3…      ┆ 0f3…      ┆ d2c…      ┆           ┆   ┆ 699…      ┆           ┆           ┆          │
│ 0x4d9e776 ┆ 0x0003b5a ┆ 0xa9ac43f ┆ 176265704 ┆ … ┆ 0xba6db30 ┆ 176268177 ┆ 2.8944e21 ┆ 24732    │
│ a1cf0894d ┆ a5e30e97f ┆ 5b5e38155 ┆ 3         ┆   ┆ 2ed58bc70 ┆ 5         ┆           ┆          │
│ 121f1341e ┆ cc596bb5d ┆ a288d1a01 ┆           ┆   ┆ bc419fc4c ┆           ┆           ┆          │
│ 2be…      ┆ 0f3…      ┆ d2c…      ┆           ┆   ┆ 2ad…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
# Analyze the statistical distribution of temporal delays for motif candidates
reciprocity_candidates.select([
    pl.len().alias("n_reciprocity_candidates"),
    pl.col("delay_seconds").min().alias("min_delay"),
    pl.col("delay_seconds").median().alias("median_delay"),
    pl.col("delay_seconds").quantile(0.75).alias("q75_delay"),
    pl.col("delay_seconds").quantile(0.90).alias("q90_delay"),
    pl.col("delay_seconds").quantile(0.95).alias("q95_delay"),
    pl.col("delay_seconds").quantile(0.99).alias("q99_delay"),
    pl.col("delay_seconds").max().alias("max_delay")
])

shape: (1, 8)
┌─────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ n_reciproci ┆ min_delay ┆ median_del ┆ q75_delay ┆ q90_delay ┆ q95_delay ┆ q99_delay ┆ max_delay │
│ ty_candidat ┆ ---       ┆ ay         ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ es          ┆ i64       ┆ ---        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ i64       │
│ ---         ┆           ┆ f64        ┆           ┆           ┆           ┆           ┆           │
│ u32         ┆           ┆            ┆           ┆           ┆           ┆           ┆           │
╞═════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 69886       ┆ 12        ┆ 1932.0     ┆ 27492.0   ┆ 68808.0   ┆ 83256.0   ┆ 85932.0   ┆ 86400     │
└─────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [16]:
# Define exploratory time window buckets to evaluate distribution patterns
delta_windows = {
    "10m": 10 * 60,
    "20m": 20 * 60,
    "1h": 60 * 60,
    "6h": 6 * 60 * 60,
    "24h": 24 * 60 * 60
}

reciprocity_summary = []

for name, delta in delta_windows.items():
    temp = reciprocity_candidates.filter(pl.col("delay_seconds") <= delta)
    
    # Extract the quantitative row count representing valid reciprocity motifs found
    n_motifs = temp.height
    
    # Calculate unique participating addresses inside the current temporal subset
    n_unique_addresses = (
        pl.concat([
            temp.select(pl.col("a").alias("address")),
            temp.select(pl.col("b").alias("address"))
        ])
        .select(pl.col("address").n_unique())
        .item()
        if n_motifs > 0 else 0
    )
    
    # Aggregate the cumulative financial transaction volume of the matched pairs in Wei units
    total_weight = temp.select((pl.col("value_1") + pl.col("value_2")).sum()).item() if n_motifs > 0 else 0
    
    reciprocity_summary.append({
        "delta": name,
        "delta_seconds": delta,
        "reciprocity_motifs": n_motifs,
        "unique_addresses": n_unique_addresses,
        "total_weight_wei": total_weight
    })

reciprocity_summary = pl.DataFrame(reciprocity_summary)

reciprocity_summary

shape: (5, 5)
┌───────┬───────────────┬────────────────────┬──────────────────┬──────────────────┐
│ delta ┆ delta_seconds ┆ reciprocity_motifs ┆ unique_addresses ┆ total_weight_wei │
│ ---   ┆ ---           ┆ ---                ┆ ---              ┆ ---              │
│ str   ┆ i64           ┆ i64                ┆ i64              ┆ f64              │
╞═══════╪═══════════════╪════════════════════╪══════════════════╪══════════════════╡
│ 10m   ┆ 600           ┆ 25813              ┆ 18385            ┆ 2.5770e22        │
│ 20m   ┆ 1200          ┆ 30865              ┆ 20418            ┆ 3.1496e22        │
│ 1h    ┆ 3600          ┆ 38500              ┆ 24301            ┆ 4.5501e22        │
│ 6h    ┆ 21600         ┆ 50833              ┆ 28722            ┆ 1.7523e23        │
│ 24h   ┆ 86400         ┆ 69886              ┆ 36737            ┆ 3.0727e23        │
└───────┴───────────────┴────────────────────┴──────────────────┴──────────────────┘

### 4.2 Linear Chain Motif Discovery

Prepare shifted transaction logs to isolate cascading relational transfers where node B receives funds from node A and subsequently transfers assets to a third distinct node C within the maximum lookahead window.

In [17]:
# Format the incoming left-hand side of the linear transmission chain
left_chain = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_1"),
        pl.col("source").alias("a"),
        pl.col("target").alias("b"),
        pl.col("timestamp").alias("t1"),
        pl.col("value_wei").alias("value_1")
    ])
    .sort(["b", "t1"])
)

# Format the corresponding right-hand side of the linear transmission chain
right_chain = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_2"),
        pl.col("source").alias("b"),
        pl.col("target").alias("c"),
        pl.col("timestamp").alias("t2"),
        pl.col("value_wei").alias("value_2")
    ])
    .sort(["b", "t2"])
)

# Identify valid linear chain sequences using an asof execution strategy
chain_candidates = (
    left_chain
    .join_asof(
        right_chain,
        left_on="t1",
        right_on="t2",
        by="b",
        strategy="forward",
        tolerance=max_delta
    )
    .filter(pl.col("t2").is_not_null())
    .filter(pl.col("t2") > pl.col("t1"))
    .filter(pl.col("a") != pl.col("c"))
    .with_columns((pl.col("t2") - pl.col("t1")).alias("delay_seconds"))
)

chain_candidates.head()

/var/folders/3k/bctm07x95zjcttz_6djk0y180000gn/T/ipykernel_20074/3432039656.py:29: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  left_chain

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash_1    ┆ a         ┆ b         ┆ t1        ┆ … ┆ c         ┆ t2        ┆ value_2   ┆ delay_se │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ conds    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ i64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0x665d4cd ┆ 0x8c1ddca ┆ 0x0000000 ┆ 176255245 ┆ … ┆ 0x1cc5c8a ┆ 176256749 ┆ 1.8700e16 ┆ 15048    │
│ 0d13e981f ┆ 691645165 ┆ 000000773 ┆ 1         ┆   ┆ e16b8c585 ┆ 9         ┆           ┆          │
│ dff2466ee ┆ 8c667a2cc ┆ 6e2f9aa56 ┆           ┆   ┆ 7c41981ca ┆           ┆           ┆          │
│ a31…      ┆ 8e8…      ┆ 30b…      ┆           ┆   ┆ fe9…      ┆           ┆           ┆          │
│ 0x54e2edd ┆ 0x8c1ddca ┆ 0x0000000 ┆ 176255255 ┆ … ┆ 0x1cc5c8a ┆ 176256749 ┆ 1.8700e16 ┆ 14940    │
│ 82d685a5a ┆ 691645165 ┆ 000000773 ┆ 9         ┆   ┆ e16b8c585 ┆ 9         ┆           ┆          │
│ aa8b945d5 ┆ 8c667a2cc ┆ 6e2f9aa56 ┆           ┆   ┆ 7c41981ca ┆           ┆           ┆          │
│ 906…      ┆ 8e8…      ┆ 30b…      ┆           ┆   ┆ fe9…      ┆           ┆           ┆          │
│ 0x886abe0 ┆ 0x89065b6 ┆ 0x0000000 ┆ 176256818 ┆ … ┆ 0x89b4afd ┆ 176259745 ┆ 5.0000e15 ┆ 29268    │
│ bc09ed7fa ┆ 75f7a11b2 ┆ 000000773 ┆ 3         ┆   ┆ 880e18e31 ┆ 1         ┆           ┆          │
│ e01a4fef7 ┆ 53eb325ef ┆ 6e2f9aa56 ┆           ┆   ┆ bc249d978 ┆           ┆           ┆          │
│ 9b9…      ┆ 0ec…      ┆ 30b…      ┆           ┆   ┆ d7f…      ┆           ┆           ┆          │
│ 0x6bd521e ┆ 0x7b80527 ┆ 0x0000000 ┆ 176270859 ┆ … ┆ 0x4cd00e3 ┆ 176270869 ┆ 2.0000e18 ┆ 96       │
│ ce31968eb ┆ 7add586ec ┆ 00008ff37 ┆ 5         ┆   ┆ 87622c35b ┆ 1         ┆           ┆          │
│ c4cbbd8e5 ┆ ca724436a ┆ b8d9c2f8d ┆           ┆   ┆ ddb9b4c96 ┆           ┆           ┆          │
│ f73…      ┆ 445…      ┆ 166…      ┆           ┆   ┆ 2c1…      ┆           ┆           ┆          │
│ 0xf9b3140 ┆ 0x00643c2 ┆ 0x0000000 ┆ 176271913 ┆ … ┆ 0x2786d48 ┆ 176271914 ┆ 9.0460e11 ┆ 12       │
│ bdc712cb3 ┆ 40e93bf5b ┆ 00020a61d ┆ 1         ┆   ┆ 2f46031b8 ┆ 3         ┆           ┆          │
│ b540d61f1 ┆ 5ed7d3594 ┆ 9ad9371a4 ┆           ┆   ┆ 402c3ce6a ┆           ┆           ┆          │
│ 388…      ┆ 4dd…      ┆ 10c…      ┆           ┆   ┆ 29a…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Extract the statistical distribution characteristics of the elapsed time delay between the incoming and outgoing steps of linear chains to map out behavioral velocities.

In [18]:
chain_candidates.select([
    pl.len().alias("n_chain_candidates"),
    pl.col("delay_seconds").min().alias("min_delay"),
    pl.col("delay_seconds").median().alias("median_delay"),
    pl.col("delay_seconds").quantile(0.75).alias("q75_delay"),
    pl.col("delay_seconds").quantile(0.90).alias("q90_delay"),
    pl.col("delay_seconds").quantile(0.95).alias("q95_delay"),
    pl.col("delay_seconds").quantile(0.99).alias("q99_delay"),
    pl.col("delay_seconds").max().alias("max_delay")
])

shape: (1, 8)
┌─────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ n_chain_can ┆ min_delay ┆ median_del ┆ q75_delay ┆ q90_delay ┆ q95_delay ┆ q99_delay ┆ max_delay │
│ didates     ┆ ---       ┆ ay         ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ---         ┆ i64       ┆ ---        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ i64       │
│ u32         ┆           ┆ f64        ┆           ┆           ┆           ┆           ┆           │
╞═════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 934700      ┆ 12        ┆ 264.0      ┆ 2004.0    ┆ 24192.0   ┆ 45144.0   ┆ 78036.0   ┆ 86400     │
└─────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [19]:
# Initialize a collection array to save structural results across tested time frames
chain_summary = []

# Loop across each designated exploratory time threshold bucket
for name, delta in delta_windows.items():
    temp = chain_candidates.filter(pl.col("delay_seconds") <= delta)
    
    n_motifs = temp.height
    
    # Extract unique participating nodes across all three positions in the chain layout
    n_unique_addresses = (
        pl.concat([
            temp.select(pl.col("a").alias("address")),
            temp.select(pl.col("b").alias("address")),
            temp.select(pl.col("c").alias("address"))
        ])
        .select(pl.col("address").n_unique())
        .item()
        if n_motifs > 0 else 0
    )
    
    # Compute the total value of assets transferred across both legs of the chain combined
    total_weight = temp.select((pl.col("value_1") + pl.col("value_2")).sum()).item() if n_motifs > 0 else 0
    
    chain_summary.append({
        "delta": name,
        "delta_seconds": delta,
        "chain_motifs": n_motifs,
        "unique_addresses": n_unique_addresses,
        "total_weight_wei": total_weight
    })

chain_summary = pl.DataFrame(chain_summary)

chain_summary

shape: (5, 5)
┌───────┬───────────────┬──────────────┬──────────────────┬──────────────────┐
│ delta ┆ delta_seconds ┆ chain_motifs ┆ unique_addresses ┆ total_weight_wei │
│ ---   ┆ ---           ┆ ---          ┆ ---              ┆ ---              │
│ str   ┆ i64           ┆ i64          ┆ i64              ┆ f64              │
╞═══════╪═══════════════╪══════════════╪══════════════════╪══════════════════╡
│ 10m   ┆ 600           ┆ 573681       ┆ 415945           ┆ 3.3189e24        │
│ 20m   ┆ 1200          ┆ 660679       ┆ 462022           ┆ 4.0568e24        │
│ 1h    ┆ 3600          ┆ 741291       ┆ 508914           ┆ 4.6965e24        │
│ 6h    ┆ 21600         ┆ 836138       ┆ 555915           ┆ 5.1304e24        │
│ 24h   ┆ 86400         ┆ 934700       ┆ 607368           ┆ 5.5518e24        │
└───────┴───────────────┴──────────────┴──────────────────┴──────────────────┘

### 4.3 Fan-In and Fan-Out Structural Sensitivity Analysis

In [20]:
# Initialize a data repository array to store structural metrics for fan structures
fan_summary = []

# Loop through each predefined exploratory time delta parameter block
for name, delta in delta_windows.items():
    # Compute discrete time bins by performing integer division on continuous transaction timestamps
    temp = (
        motif_sample
        .with_columns((pl.col("timestamp") // delta).alias("time_bin"))
    )
    
    # Identify Fan-In structures where multiple sources transfer funds to a common target in the same time bin
    fan_in = (
        temp
        .group_by(["target", "time_bin"])
        .agg([
            pl.len().alias("n_tx"),
            pl.col("source").n_unique().alias("n_unique_sources"),
            pl.col("value_wei").sum().alias("total_value_wei")
        ])
        .filter(pl.col("n_unique_sources") >= 3)
    )
    
    # Identify Fan-Out structures where a single source splits funds among multiple targets in the same time bin
    fan_out = (
        temp
        .group_by(["source", "time_bin"])
        .agg([
            pl.len().alias("n_tx"),
            pl.col("target").n_unique().alias("n_unique_targets"),
            pl.col("value_wei").sum().alias("total_value_wei")
        ])
        .filter(pl.col("n_unique_targets") >= 3)
    )
    
    # Collect the calculated geometric shape occurrences into the comparative array
    fan_summary.append({
        "delta": name,
        "delta_seconds": delta,
        "fan_in_windows": fan_in.height,
        "fan_in_addresses": fan_in.select(pl.col("target").n_unique()).item() if fan_in.height > 0 else 0,
        "fan_out_windows": fan_out.height,
        "fan_out_addresses": fan_out.select(pl.col("source").n_unique()).item() if fan_out.height > 0 else 0
    })

fan_summary = pl.DataFrame(fan_summary)

fan_summary

shape: (5, 6)
┌───────┬───────────────┬────────────────┬──────────────────┬─────────────────┬───────────────────┐
│ delta ┆ delta_seconds ┆ fan_in_windows ┆ fan_in_addresses ┆ fan_out_windows ┆ fan_out_addresses │
│ ---   ┆ ---           ┆ ---            ┆ ---              ┆ ---             ┆ ---               │
│ str   ┆ i64           ┆ i64            ┆ i64              ┆ i64             ┆ i64               │
╞═══════╪═══════════════╪════════════════╪══════════════════╪═════════════════╪═══════════════════╡
│ 10m   ┆ 600           ┆ 105333         ┆ 7213             ┆ 105790          ┆ 39195             │
│ 20m   ┆ 1200          ┆ 90775          ┆ 9395             ┆ 106134          ┆ 48433             │
│ 1h    ┆ 3600          ┆ 68831          ┆ 13178            ┆ 105966          ┆ 60053             │
│ 6h    ┆ 21600         ┆ 45748          ┆ 19728            ┆ 102570          ┆ 74920             │
│ 24h   ┆ 86400         ┆ 37695          ┆ 25574            ┆ 102137          ┆ 86954             │
└───────┴───────────────┴────────────────┴──────────────────┴─────────────────┴───────────────────┘

### 4.4 Repeated Same-Direction Motif Discovery

Isolate repetitive sequential transaction behaviors directed from the exact same sender address to the exact same receiver address using localized window shifting over entity pairs.

In [21]:
max_delta = 24 * 60 * 60

# Identify continuous, consecutive repetitive operations across stable directed pairs
repeat_candidates = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_1"),
        pl.col("source").alias("a"),
        pl.col("target").alias("b"),
        pl.col("timestamp").alias("t1"),
        pl.col("value_wei").alias("value_1")
    ])
    .sort(["a", "b", "t1", "hash_1"])
    .with_columns([
        pl.col("hash_1").shift(-1).over(["a", "b"]).alias("hash_2"),
        pl.col("t1").shift(-1).over(["a", "b"]).alias("t2"),
        pl.col("value_1").shift(-1).over(["a", "b"]).alias("value_2")
    ])
    .filter(pl.col("t2").is_not_null())
    .filter(pl.col("t2") > pl.col("t1"))
    .with_columns(
        (pl.col("t2") - pl.col("t1")).alias("delay_seconds")
    )
    .filter(pl.col("delay_seconds") <= max_delta)
)
# Preview the initial rows of mapped same-direction repetitive transfers
repeat_candidates.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash_1    ┆ a         ┆ b         ┆ t1        ┆ … ┆ hash_2    ┆ t2        ┆ value_2   ┆ delay_se │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ conds    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ i64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0xe307c41 ┆ 0x0000000 ┆ 0xeaf7e30 ┆ 176262031 ┆ … ┆ 0x9f40742 ┆ 176262059 ┆ 4.0000e15 ┆ 288      │
│ 1712628e2 ┆ 000000773 ┆ 4ea5f0670 ┆ 1         ┆   ┆ 2581d664c ┆ 9         ┆           ┆          │
│ 2cc08db4a ┆ 6e2f9aa56 ┆ b223d5024 ┆           ┆   ┆ 7572db1c2 ┆           ┆           ┆          │
│ 59f…      ┆ 30b…      ┆ 633…      ┆           ┆   ┆ cc9…      ┆           ┆           ┆          │
│ 0xe6c4f78 ┆ 0x0000000 ┆ 0x0000000 ┆ 176254729 ┆ … ┆ 0x8b7d1c7 ┆ 176255025 ┆ 9.4437377 ┆ 2964     │
│ 16125f111 ┆ 000000792 ┆ 000efa780 ┆ 1         ┆   ┆ 30ac9e2d4 ┆ 5         ┆ e7        ┆          │
│ e7f690426 ┆ b90728399 ┆ a8e6f50fc ┆           ┆   ┆ 2b1fe0e66 ┆           ┆           ┆          │
│ 339…      ┆ 935…      ┆ 5de…      ┆           ┆   ┆ 16a…      ┆           ┆           ┆          │
│ 0x8b7d1c7 ┆ 0x0000000 ┆ 0x0000000 ┆ 176255025 ┆ … ┆ 0x7e02bc1 ┆ 176255165 ┆ 9.1422721 ┆ 1404     │
│ 30ac9e2d4 ┆ 000000792 ┆ 000efa780 ┆ 5         ┆   ┆ bf5c05ce1 ┆ 9         ┆ e7        ┆          │
│ 2b1fe0e66 ┆ b90728399 ┆ a8e6f50fc ┆           ┆   ┆ 309240945 ┆           ┆           ┆          │
│ 16a…      ┆ 935…      ┆ 5de…      ┆           ┆   ┆ b00…      ┆           ┆           ┆          │
│ 0x7e02bc1 ┆ 0x0000000 ┆ 0x0000000 ┆ 176255165 ┆ … ┆ 0x19a37f9 ┆ 176255186 ┆ 6.0751873 ┆ 204      │
│ bf5c05ce1 ┆ 000000792 ┆ 000efa780 ┆ 9         ┆   ┆ 5efbb7f9b ┆ 3         ┆ e7        ┆          │
│ 309240945 ┆ b90728399 ┆ a8e6f50fc ┆           ┆   ┆ e62c1b5ff ┆           ┆           ┆          │
│ b00…      ┆ 935…      ┆ 5de…      ┆           ┆   ┆ c27…      ┆           ┆           ┆          │
│ 0x19a37f9 ┆ 0x0000000 ┆ 0x0000000 ┆ 176255186 ┆ … ┆ 0x7d0e26b ┆ 176255276 ┆ 1.0446438 ┆ 900      │
│ 5efbb7f9b ┆ 000000792 ┆ 000efa780 ┆ 3         ┆   ┆ 2e11db9ad ┆ 3         ┆ 5e8       ┆          │
│ e62c1b5ff ┆ b90728399 ┆ a8e6f50fc ┆           ┆   ┆ baf9045ea ┆           ┆           ┆          │
│ c27…      ┆ 935…      ┆ 5de…      ┆           ┆   ┆ 9a3…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
# Initialize a metric tracking array to map out direct repetition frequency patterns
repeat_summary = []
# Iterate across each step threshold window item inside the dictionary collection
for name, delta in delta_windows.items():
    temp = repeat_candidates.filter(pl.col("delay_seconds") <= delta)
    
    n_motifs = temp.height
    # Calculate unique participating addresses contributing to these repetitive patterns
    n_unique_addresses = (
        pl.concat([
            temp.select(pl.col("a").alias("address")),
            temp.select(pl.col("b").alias("address"))
        ])
        .select(pl.col("address").n_unique())
        .item()
        if n_motifs > 0 else 0
    )
    # Compute the total value of assets transferred across consecutive repeated operations
    total_weight = (
        temp.select((pl.col("value_1") + pl.col("value_2")).sum()).item()
        if n_motifs > 0 else 0
    )
    # Log the metrics into our collection dictionary tracking structure
    repeat_summary.append({
        "delta": name,
        "delta_seconds": delta,
        "repeat_motifs": n_motifs,
        "unique_addresses": n_unique_addresses,
        "total_weight_wei": total_weight
    })

repeat_summary = pl.DataFrame(repeat_summary)

repeat_summary

shape: (5, 5)
┌───────┬───────────────┬───────────────┬──────────────────┬──────────────────┐
│ delta ┆ delta_seconds ┆ repeat_motifs ┆ unique_addresses ┆ total_weight_wei │
│ ---   ┆ ---           ┆ ---           ┆ ---              ┆ ---              │
│ str   ┆ i64           ┆ i64           ┆ i64              ┆ f64              │
╞═══════╪═══════════════╪═══════════════╪══════════════════╪══════════════════╡
│ 10m   ┆ 600           ┆ 994858        ┆ 128279           ┆ 4.7135e23        │
│ 20m   ┆ 1200          ┆ 1158715       ┆ 148572           ┆ 6.6622e23        │
│ 1h    ┆ 3600          ┆ 1387575       ┆ 178614           ┆ 1.2207e24        │
│ 6h    ┆ 21600         ┆ 1688894       ┆ 267275           ┆ 1.8668e24        │
│ 24h   ┆ 86400         ┆ 1870059       ┆ 306467           ┆ 2.5623e24        │
└───────┴───────────────┴───────────────┴──────────────────┴──────────────────┘

### 4.5 Directed 3-Cycle Motif Optimization

In [23]:
max_delta = 24 * 60 * 60

# Format the first leg of the 3-cycle sequence
edge_1 = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_1"),
        pl.col("source").alias("a"),
        pl.col("target").alias("b"),
        pl.col("timestamp").alias("t1"),
        pl.col("value_wei").alias("value_1")
    ])
    .sort(["b", "t1"])
)

# Format the second leg of the 3-cycle sequence
edge_2 = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_2"),
        pl.col("source").alias("b"),
        pl.col("target").alias("c"),
        pl.col("timestamp").alias("t2"),
        pl.col("value_wei").alias("value_2")
    ])
    .sort(["b", "t2"])
)

# Identify valid two-step paths using an asof join strategy
two_step_paths = (
    edge_1
    .join_asof(
        edge_2,
        left_on="t1",
        right_on="t2",
        by="b",
        strategy="forward",
        tolerance=max_delta
    )
    .filter(pl.col("t2").is_not_null())
    .filter(pl.col("t2") > pl.col("t1"))
    .filter(pl.col("a") != pl.col("b"))
    .filter(pl.col("b") != pl.col("c"))
    .filter(pl.col("a") != pl.col("c"))
    .with_columns((pl.col("t2") - pl.col("t1")).alias("delay_12"))
)

two_step_paths.head()

/var/folders/3k/bctm07x95zjcttz_6djk0y180000gn/T/ipykernel_20074/1203483548.py:31: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  edge_1

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash_1    ┆ a         ┆ b         ┆ t1        ┆ … ┆ c         ┆ t2        ┆ value_2   ┆ delay_12 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ i64       ┆ f64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0x665d4cd ┆ 0x8c1ddca ┆ 0x0000000 ┆ 176255245 ┆ … ┆ 0x1cc5c8a ┆ 176256749 ┆ 1.8700e16 ┆ 15048    │
│ 0d13e981f ┆ 691645165 ┆ 000000773 ┆ 1         ┆   ┆ e16b8c585 ┆ 9         ┆           ┆          │
│ dff2466ee ┆ 8c667a2cc ┆ 6e2f9aa56 ┆           ┆   ┆ 7c41981ca ┆           ┆           ┆          │
│ a31…      ┆ 8e8…      ┆ 30b…      ┆           ┆   ┆ fe9…      ┆           ┆           ┆          │
│ 0x54e2edd ┆ 0x8c1ddca ┆ 0x0000000 ┆ 176255255 ┆ … ┆ 0x1cc5c8a ┆ 176256749 ┆ 1.8700e16 ┆ 14940    │
│ 82d685a5a ┆ 691645165 ┆ 000000773 ┆ 9         ┆   ┆ e16b8c585 ┆ 9         ┆           ┆          │
│ aa8b945d5 ┆ 8c667a2cc ┆ 6e2f9aa56 ┆           ┆   ┆ 7c41981ca ┆           ┆           ┆          │
│ 906…      ┆ 8e8…      ┆ 30b…      ┆           ┆   ┆ fe9…      ┆           ┆           ┆          │
│ 0x886abe0 ┆ 0x89065b6 ┆ 0x0000000 ┆ 176256818 ┆ … ┆ 0x89b4afd ┆ 176259745 ┆ 5.0000e15 ┆ 29268    │
│ bc09ed7fa ┆ 75f7a11b2 ┆ 000000773 ┆ 3         ┆   ┆ 880e18e31 ┆ 1         ┆           ┆          │
│ e01a4fef7 ┆ 53eb325ef ┆ 6e2f9aa56 ┆           ┆   ┆ bc249d978 ┆           ┆           ┆          │
│ 9b9…      ┆ 0ec…      ┆ 30b…      ┆           ┆   ┆ d7f…      ┆           ┆           ┆          │
│ 0x6bd521e ┆ 0x7b80527 ┆ 0x0000000 ┆ 176270859 ┆ … ┆ 0x4cd00e3 ┆ 176270869 ┆ 2.0000e18 ┆ 96       │
│ ce31968eb ┆ 7add586ec ┆ 00008ff37 ┆ 5         ┆   ┆ 87622c35b ┆ 1         ┆           ┆          │
│ c4cbbd8e5 ┆ ca724436a ┆ b8d9c2f8d ┆           ┆   ┆ ddb9b4c96 ┆           ┆           ┆          │
│ f73…      ┆ 445…      ┆ 166…      ┆           ┆   ┆ 2c1…      ┆           ┆           ┆          │
│ 0xf9b3140 ┆ 0x00643c2 ┆ 0x0000000 ┆ 176271913 ┆ … ┆ 0x2786d48 ┆ 176271914 ┆ 9.0460e11 ┆ 12       │
│ bdc712cb3 ┆ 40e93bf5b ┆ 00020a61d ┆ 1         ┆   ┆ 2f46031b8 ┆ 3         ┆           ┆          │
│ b540d61f1 ┆ 5ed7d3594 ┆ 9ad9371a4 ┆           ┆   ┆ 402c3ce6a ┆           ┆           ┆          │
│ 388…      ┆ 4dd…      ┆ 10c…      ┆           ┆   ┆ 29a…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
# Format the third, closing leg of the 3-cycle sequence
edge_3 = (
    motif_sample
    .select([
        pl.col("hash").alias("hash_3"),
        pl.col("source").alias("c"),
        pl.col("target").alias("a"),
        pl.col("timestamp").alias("t3"),
        pl.col("value_wei").alias("value_3")
    ])
    .sort(["c", "a", "t3"])
)

# Complete the directed 3-cycle mapping by joining the closing leg
cycle_candidates = (
    two_step_paths
    .sort(["c", "a", "t2"])
    .join_asof(
        edge_3,
        left_on="t2",
        right_on="t3",
        by=["c", "a"],
        strategy="forward",
        tolerance=max_delta
    )
    .filter(pl.col("t3").is_not_null())
    .filter(pl.col("t3") > pl.col("t2"))
    .filter(pl.col("hash_1") != pl.col("hash_2"))
    .filter(pl.col("hash_1") != pl.col("hash_3"))
    .filter(pl.col("hash_2") != pl.col("hash_3"))
    .with_columns((pl.col("t3") - pl.col("t1")).alias("delay_seconds"))
)

cycle_candidates.head()

/var/folders/3k/bctm07x95zjcttz_6djk0y180000gn/T/ipykernel_20074/2433222471.py:16: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  two_step_paths

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash_1    ┆ a         ┆ b         ┆ t1        ┆ … ┆ hash_3    ┆ t3        ┆ value_3   ┆ delay_se │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ conds    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ str       ┆ i64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0x7041009 ┆ 0xf584f87 ┆ 0xbcd9865 ┆ 176273176 ┆ … ┆ 0x3f84b28 ┆ 176276930 ┆ 7.3699e18 ┆ 37536    │
│ b387f3412 ┆ 28b874a6a ┆ 63ba93af5 ┆ 7         ┆   ┆ 8e8798a1a ┆ 3         ┆           ┆          │
│ b668a20f4 ┆ 5c7a8d4d3 ┆ c6c92b16a ┆           ┆   ┆ a1162d04c ┆           ┆           ┆          │
│ bb2…      ┆ 87c…      ┆ b06…      ┆           ┆   ┆ f28…      ┆           ┆           ┆          │
│ 0xeb314ad ┆ 0xf584f87 ┆ 0xbcd9865 ┆ 176273417 ┆ … ┆ 0x3f84b28 ┆ 176276930 ┆ 7.3699e18 ┆ 35124    │
│ 7199e6178 ┆ 28b874a6a ┆ 63ba93af5 ┆ 9         ┆   ┆ 8e8798a1a ┆ 3         ┆           ┆          │
│ fe00d13e5 ┆ 5c7a8d4d3 ┆ c6c92b16a ┆           ┆   ┆ a1162d04c ┆           ┆           ┆          │
│ a05…      ┆ 87c…      ┆ b06…      ┆           ┆   ┆ f28…      ┆           ┆           ┆          │
│ 0x23367ed ┆ 0xef317e4 ┆ 0x2a107c3 ┆ 176267871 ┆ … ┆ 0xc9d9367 ┆ 176267899 ┆ 2.5427e16 ┆ 276      │
│ ad1863917 ┆ 33b0836f2 ┆ 285f67a5c ┆ 5         ┆   ┆ 41cbeee46 ┆ 1         ┆           ┆          │
│ bbf7d0680 ┆ 94866d43f ┆ e030943ef ┆           ┆   ┆ 3d55c7b6b ┆           ┆           ┆          │
│ 8d8…      ┆ 67d…      ┆ f36…      ┆           ┆   ┆ 867…      ┆           ┆           ┆          │
│ 0xdc334c4 ┆ 0x07e6beb ┆ 0xe5feb16 ┆ 176261098 ┆ … ┆ 0x1c3fa7b ┆ 176270864 ┆ 1.9860e17 ┆ 97656    │
│ ca90b7864 ┆ 786b58cbd ┆ 182f367d5 ┆ 7         ┆   ┆ 3faca3989 ┆ 3         ┆           ┆          │
│ e2c11ac53 ┆ d83192137 ┆ d98148f36 ┆           ┆   ┆ 8db5a1395 ┆           ┆           ┆          │
│ bb9…      ┆ 00b…      ┆ 3c9…      ┆           ┆   ┆ bc4…      ┆           ┆           ┆          │
│ 0xcac208a ┆ 0x07e6beb ┆ 0xe5feb16 ┆ 176265687 ┆ … ┆ 0x1c3fa7b ┆ 176270864 ┆ 1.9860e17 ┆ 51768    │
│ d35f26de8 ┆ 786b58cbd ┆ 182f367d5 ┆ 5         ┆   ┆ 3faca3989 ┆ 3         ┆           ┆          │
│ 58115a72c ┆ d83192137 ┆ d98148f36 ┆           ┆   ┆ 8db5a1395 ┆           ┆           ┆          │
│ 96d…      ┆ 00b…      ┆ 3c9…      ┆           ┆   ┆ bc4…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
cycle_summary = []

# Iterate across each step threshold window item inside the dictionary collection
for name, delta in delta_windows.items():
    temp = cycle_candidates.filter(pl.col("delay_seconds") <= delta)
    
    n_motifs = temp.height
    
    # Calculate unique participating addresses across all positions in the cycle
    n_unique_addresses = (
        pl.concat([
            temp.select(pl.col("a").alias("address")),
            temp.select(pl.col("b").alias("address")),
            temp.select(pl.col("c").alias("address"))
        ])
        .select(pl.col("address").n_unique())
        .item()
        if n_motifs > 0 else 0
    )
    
    # Compute the total value of assets transferred across all three legs of the cycle
    total_weight = (
        temp.select((pl.col("value_1") + pl.col("value_2") + pl.col("value_3")).sum()).item()
        if n_motifs > 0 else 0
    )
    
    # Record the summary metrics into the tracking dictionary array
    cycle_summary.append({
        "delta": name,
        "delta_seconds": delta,
        "cycle_motifs": n_motifs,
        "unique_addresses": n_unique_addresses,
        "total_weight_wei": total_weight
    })

cycle_summary = pl.DataFrame(cycle_summary)

cycle_summary

shape: (5, 5)
┌───────┬───────────────┬──────────────┬──────────────────┬──────────────────┐
│ delta ┆ delta_seconds ┆ cycle_motifs ┆ unique_addresses ┆ total_weight_wei │
│ ---   ┆ ---           ┆ ---          ┆ ---              ┆ ---              │
│ str   ┆ i64           ┆ i64          ┆ i64              ┆ f64              │
╞═══════╪═══════════════╪══════════════╪══════════════════╪══════════════════╡
│ 10m   ┆ 600           ┆ 1799         ┆ 2189             ┆ 1.6030e21        │
│ 20m   ┆ 1200          ┆ 2858         ┆ 3226             ┆ 3.5111e21        │
│ 1h    ┆ 3600          ┆ 5107         ┆ 4853             ┆ 1.1841e22        │
│ 6h    ┆ 21600         ┆ 8460         ┆ 6743             ┆ 6.6907e22        │
│ 24h   ┆ 86400         ┆ 11889        ┆ 8804             ┆ 1.3845e23        │
└───────┴───────────────┴──────────────┴──────────────────┴──────────────────┘

### 4.6 Final Parameter Configuration Selection

In [26]:
main_delta_name = "1h"
main_delta = 60 * 60

chosen_delta = {
    "main_delta_name": "1h",
    "main_delta_seconds": 60 * 60,
    "reason": "Best empirical trade-off between motif coverage and temporal specificity"
}

chosen_delta

{'main_delta_name': '1h',
 'main_delta_seconds': 3600,
 'reason': 'Best empirical trade-off between motif coverage and temporal specificity'}

Evaluating multiple structural layout formats (Reciprocity, Chains, Fans, Repetitions, and Cycles) shows that structural pattern density trends stabilize near the 1-hour (Δ=3600s) threshold. This window serves as the optimal hyperparameter configuration, providing strong signal separation for fraud detection models by capturing coordinated transactional behavior while filtering out background noise from unrelated market activity.

In [27]:
window_selection_summary = (
    reciprocity_summary
    .select(["delta", "delta_seconds", "reciprocity_motifs"])
    .join(
        chain_summary.select(["delta", "chain_motifs"]),
        on="delta",
        how="left"
    )
    .join(
        fan_summary.select(["delta", "fan_in_windows", "fan_out_windows"]),
        on="delta",
        how="left"
    )
    .join(
        repeat_summary.select(["delta", "repeat_motifs"]),
        on="delta",
        how="left"
    )
    .join(
        cycle_summary.select(["delta", "cycle_motifs"]),
        on="delta",
        how="left"
    )
)

window_selection_summary

shape: (5, 8)
┌───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ delta ┆ delta_seco ┆ reciprocit ┆ chain_moti ┆ fan_in_win ┆ fan_out_wi ┆ repeat_mot ┆ cycle_moti │
│ ---   ┆ nds        ┆ y_motifs   ┆ fs         ┆ dows       ┆ ndows      ┆ ifs        ┆ fs         │
│ str   ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆ i64        ┆ i64        ┆ i64        ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 10m   ┆ 600        ┆ 25813      ┆ 573681     ┆ 105333     ┆ 105790     ┆ 994858     ┆ 1799       │
│ 20m   ┆ 1200       ┆ 30865      ┆ 660679     ┆ 90775      ┆ 106134     ┆ 1158715    ┆ 2858       │
│ 1h    ┆ 3600       ┆ 38500      ┆ 741291     ┆ 68831      ┆ 105966     ┆ 1387575    ┆ 5107       │
│ 6h    ┆ 21600      ┆ 50833      ┆ 836138     ┆ 45748      ┆ 102570     ┆ 1688894    ┆ 8460       │
│ 24h   ┆ 86400      ┆ 69886      ┆ 934700     ┆ 37695      ┆ 102137     ┆ 1870059    ┆ 11889      │
└───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [28]:
window_selection_for_slide = (
    window_selection_summary
    .with_columns([
        (
            pl.col("reciprocity_motifs")
            + pl.col("chain_motifs")
            + pl.col("fan_in_windows")
            + pl.col("fan_out_windows")
            + pl.col("repeat_motifs")
            + pl.col("cycle_motifs")
        ).alias("total_motifs")
    ])
)

window_selection_for_slide

shape: (5, 9)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ delta ┆ delta_seco ┆ reciprocit ┆ chain_moti ┆ … ┆ fan_out_w ┆ repeat_mo ┆ cycle_mot ┆ total_mot │
│ ---   ┆ nds        ┆ y_motifs   ┆ fs         ┆   ┆ indows    ┆ tifs      ┆ ifs       ┆ ifs       │
│ str   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│       ┆ i64        ┆ i64        ┆ i64        ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10m   ┆ 600        ┆ 25813      ┆ 573681     ┆ … ┆ 105790    ┆ 994858    ┆ 1799      ┆ 1807274   │
│ 20m   ┆ 1200       ┆ 30865      ┆ 660679     ┆ … ┆ 106134    ┆ 1158715   ┆ 2858      ┆ 2050026   │
│ 1h    ┆ 3600       ┆ 38500      ┆ 741291     ┆ … ┆ 105966    ┆ 1387575   ┆ 5107      ┆ 2347270   │
│ 6h    ┆ 21600      ┆ 50833      ┆ 836138     ┆ … ┆ 102570    ┆ 1688894   ┆ 8460      ┆ 2732643   │
│ 24h   ┆ 86400      ┆ 69886      ┆ 934700     ┆ … ┆ 102137    ┆ 1870059   ┆ 11889     ┆ 3026366   │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

## 5. Transaction Subgraph Preparation

In [29]:
# Define dictionary mapping the target analytical behavioral profiles to their respective node storage files
community_files = {
    "wash_trading_846": "selected_wash_trading_community_846_nodes.csv",
    "phishing_390": "selected_phishing_community_390_nodes.csv",
    "mixer_242": "selected_mixer_community_242_nodes.csv"
}

# Initialize data container dictionaries to hold parsed DataFrames and optimized lookup index sets
community_nodes = {}
community_address_sets = {}

# Iterate over each target behavioral category to load and audit structural layouts
for name, path in community_files.items():
    nodes_df = pl.read_csv(path).with_columns([
        pl.col("address").str.to_lowercase()
    ])
    
    # Cache the processed node registry DataFrame into the storage dictionary container
    community_nodes[name] = nodes_df
    
    # Extract the normalized address series and cast it into a standard flat list configuration
    addresses = (
        nodes_df
        .select("address")
        .to_series()
        .to_list()
    )
    
    # Convert list records into an optimized hash set to achieve O(1) query lookup operations during execution loops
    community_address_sets[name] = set(addresses)
    
    print("=" * 80)
    print(name)
    print("n_nodes:", len(addresses))
    
    print(
        nodes_df
        .group_by("label")
        .agg(pl.len().alias("count"))
    )

================================================================================
wash_trading_846
n_nodes: 2820
shape: (2, 2)
┌────────┬───────┐
│ label  ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ fraud  ┆ 459   │
│ normal ┆ 2361  │
└────────┴───────┘
================================================================================
phishing_390
n_nodes: 17500
shape: (2, 2)
┌────────┬───────┐
│ label  ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ fraud  ┆ 46    │
│ normal ┆ 17454 │
└────────┴───────┘
================================================================================
mixer_242
n_nodes: 5901
shape: (2, 2)
┌────────┬───────┐
│ label  ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ fraud  ┆ 28    │
│ normal ┆ 5873  │
└────────┴───────┘

Filter the global transaction ledger to isolate activities where at least one interacting vertex intersects the target community profile set. Categorize edges dynamically into internal, outgoing, or incoming boundary type scopes based on node set constraints.

In [30]:
# Initialize data container dictionary to store isolated edge transactions for each community partition
boundary_transactions = {}

# Process each community tracking partition to parse structural subgraphs and topological boundaries
for name, address_set in community_address_sets.items():
    # Define boolean expressions checking if an interaction originates or terminates inside our target community set
    source_inside_expr = pl.col("source").is_in(address_set)
    target_inside_expr = pl.col("target").is_in(address_set)
    
    # Filter the transaction repository and append localized directional tracking columns
    tx = (
        events
        .filter(source_inside_expr | target_inside_expr)
        .with_columns([
            source_inside_expr.alias("source_inside_community"),
            target_inside_expr.alias("target_inside_community")
        ])
        .with_columns([
            # Apply conditional evaluation matching rules to group boundary connection flows
            pl.when(
                pl.col("source_inside_community") & pl.col("target_inside_community")
            )
            .then(pl.lit("internal"))
            .when(
                pl.col("source_inside_community") & ~pl.col("target_inside_community")
            )
            .then(pl.lit("outgoing"))
            .when(
                ~pl.col("source_inside_community") & pl.col("target_inside_community")
            )
            .then(pl.lit("incoming"))
            .otherwise(pl.lit("other"))
            .alias("boundary_type")
        ])
        .sort("timestamp")
    )
    
    # Save the parsed boundary transaction records dataframe to the central caching dictionary
    boundary_transactions[name] = tx
    
    # Display quantitative execution summary tables showing the distribution metrics of boundary transaction categories
    print("=" * 80)
    print(name)
    print("Boundary transactions:", tx.height)
    print(tx.group_by("boundary_type").agg(pl.len().alias("n_tx")).sort("n_tx", descending=True))
    
    display(tx.head())

================================================================================
wash_trading_846
Boundary transactions: 33681
shape: (3, 2)
┌───────────────┬───────┐
│ boundary_type ┆ n_tx  │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ internal      ┆ 28218 │
│ outgoing      ┆ 3927  │
│ incoming      ┆ 1536  │
└───────────────┴───────┘

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash      ┆ source    ┆ target    ┆ timestamp ┆ … ┆ value_eth ┆ source_in ┆ target_in ┆ boundary │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ side_comm ┆ side_comm ┆ _type    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ f64       ┆ unity     ┆ unity     ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0x195d31a ┆ 0x1e42d03 ┆ 0x7a250d5 ┆ 176254802 ┆ … ┆ 0.0       ┆ true      ┆ false     ┆ outgoing │
│ 0f3b21145 ┆ ae8b26cd8 ┆ 630b4cf53 ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ 5edfe70b5 ┆ 1bf7997f7 ┆ 9739df2c5 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 66f…      ┆ 39c…      ┆ dac…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x2f3f83e ┆ 0x5cece24 ┆ 0xfafe9e4 ┆ 176254933 ┆ … ┆ 0.0       ┆ false     ┆ true      ┆ incoming │
│ a9392924b ┆ e0085bba4 ┆ b59fa4493 ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 22b5ff5a6 ┆ ab59c24fc ┆ fa8816dba ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa1…      ┆ 20d…      ┆ be6…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0xb0383ed ┆ 0x9af9ee5 ┆ 0x7a250d5 ┆ 176254948 ┆ … ┆ 0.1499    ┆ true      ┆ false     ┆ outgoing │
│ 495733ab6 ┆ 52e4249a3 ┆ 630b4cf53 ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ a2b74d6e9 ┆ 133a84097 ┆ 9739df2c5 ┆           ┆   ┆           ┆           ┆           ┆          │
│ b16…      ┆ 29e…      ┆ dac…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x7174747 ┆ 0x7ee6f0c ┆ 0xfafe9e4 ┆ 176255014 ┆ … ┆ 0.0       ┆ true      ┆ true      ┆ internal │
│ f5d3a3e25 ┆ bf1c63ea3 ┆ b59fa4493 ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 97d546a1e ┆ dd791f7c8 ┆ fa8816dba ┆           ┆   ┆           ┆           ┆           ┆          │
│ bff…      ┆ 15c…      ┆ be6…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x7618f9a ┆ 0x7ee6f0c ┆ 0x7a250d5 ┆ 176255014 ┆ … ┆ 0.0       ┆ true      ┆ false     ┆ outgoing │
│ 984ae39c8 ┆ bf1c63ea3 ┆ 630b4cf53 ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 6e0735d3e ┆ dd791f7c8 ┆ 9739df2c5 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 49a…      ┆ 15c…      ┆ dac…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

================================================================================
phishing_390
Boundary transactions: 65504
shape: (3, 2)
┌───────────────┬───────┐
│ boundary_type ┆ n_tx  │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ internal      ┆ 28376 │
│ outgoing      ┆ 24742 │
│ incoming      ┆ 12386 │
└───────────────┴───────┘

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash      ┆ source    ┆ target    ┆ timestamp ┆ … ┆ value_eth ┆ source_in ┆ target_in ┆ boundary │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ side_comm ┆ side_comm ┆ _type    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ f64       ┆ unity     ┆ unity     ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0xf866671 ┆ 0x8f8d120 ┆ 0x5253e39 ┆ 176254691 ┆ … ┆ 0.026938  ┆ false     ┆ true      ┆ incoming │
│ 01d0df10b ┆ 6d1bce12f ┆ 5b06ee627 ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ b09461c5a ┆ f892731f8 ┆ 5dd87c69f ┆           ┆   ┆           ┆           ┆           ┆          │
│ afb…      ┆ a14…      ┆ 46f…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0xc6f8424 ┆ 0x0ada311 ┆ 0xff05652 ┆ 176254691 ┆ … ┆ 0.013469  ┆ false     ┆ true      ┆ incoming │
│ 5f231c6a3 ┆ 1b866ff1a ┆ c20ee3599 ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 32b05032b ┆ d0477f0c5 ┆ ea06816a7 ┆           ┆   ┆           ┆           ┆           ┆          │
│ ce0…      ┆ d2e…      ┆ 932…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x02ab304 ┆ 0x8f8d120 ┆ 0xd867c63 ┆ 176254694 ┆ … ┆ 0.016831  ┆ false     ┆ true      ┆ incoming │
│ c94e0076a ┆ 6d1bce12f ┆ 027aaaff6 ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ 55de684bc ┆ f892731f8 ┆ 65ebfd422 ┆           ┆   ┆           ┆           ┆           ┆          │
│ f17…      ┆ a14…      ┆ 4c9…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x5aa6202 ┆ 0x974caa5 ┆ 0xf334a84 ┆ 176254695 ┆ … ┆ 0.584896  ┆ true      ┆ false     ┆ outgoing │
│ da760798f ┆ 9e49682cd ┆ 5ff38b567 ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 8261dfb4d ┆ a0ad2bbe8 ┆ e764a1750 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 781…      ┆ 298…      ┆ 456…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x0d2f2bf ┆ 0x852dc1c ┆ 0x2defec3 ┆ 176254695 ┆ … ┆ 0.013087  ┆ false     ┆ true      ┆ incoming │
│ ffccfdfa7 ┆ 875f0117e ┆ 740f6ab34 ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ fe4004566 ┆ a08086100 ┆ 4f0afded5 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 678…      ┆ 108…      ┆ 00a…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

================================================================================
mixer_242
Boundary transactions: 70569
shape: (3, 2)
┌───────────────┬───────┐
│ boundary_type ┆ n_tx  │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ outgoing      ┆ 47765 │
│ internal      ┆ 16110 │
│ incoming      ┆ 6694  │
└───────────────┴───────┘

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hash      ┆ source    ┆ target    ┆ timestamp ┆ … ┆ value_eth ┆ source_in ┆ target_in ┆ boundary │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ side_comm ┆ side_comm ┆ _type    │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ f64       ┆ unity     ┆ unity     ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0x632c7aa ┆ 0x28c6c06 ┆ 0xee7ae85 ┆ 176254691 ┆ … ┆ 0.0       ┆ true      ┆ true      ┆ internal │
│ 0293d1867 ┆ 298d514db ┆ f2fe2239e ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ cd25e39a6 ┆ 089934071 ┆ 27d9c1e23 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2a9…      ┆ 355…      ┆ fff…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x14ac44f ┆ 0x28c6c06 ┆ 0x7a58c0b ┆ 176254693 ┆ … ┆ 0.0       ┆ true      ┆ false     ┆ outgoing │
│ 9320a3fcb ┆ 298d514db ┆ e72be218b ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ de8cf3760 ┆ 089934071 ┆ 41c608b7f ┆           ┆   ┆           ┆           ┆           ┆          │
│ c9d…      ┆ 355…      ┆ e7c…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0xcf9a4fa ┆ 0x28c6c06 ┆ 0xdac17f9 ┆ 176254693 ┆ … ┆ 0.0       ┆ true      ┆ false     ┆ outgoing │
│ 88d0fe147 ┆ 298d514db ┆ 58d2ee523 ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 24fcf3091 ┆ 089934071 ┆ a22062069 ┆           ┆   ┆           ┆           ┆           ┆          │
│ f41…      ┆ 355…      ┆ 945…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0xa42f645 ┆ 0x28c6c06 ┆ 0xd0ec028 ┆ 176254693 ┆ … ┆ 0.0       ┆ true      ┆ false     ┆ outgoing │
│ f0834d6d8 ┆ 298d514db ┆ a3d21533f ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 81514b0a4 ┆ 089934071 ┆ dd200838f ┆           ┆   ┆           ┆           ┆           ┆          │
│ 903…      ┆ 355…      ┆ 39c…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x301cd04 ┆ 0x4cbe437 ┆ 0x4cbe437 ┆ 176254693 ┆ … ┆ 0.0       ┆ true      ┆ true      ┆ internal │
│ 0f0636697 ┆ aa7a83457 ┆ aa7a83457 ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ d69296bbf ┆ 221d65720 ┆ 221d65720 ┆           ┆   ┆           ┆           ┆           ┆          │
│ d78…      ┆ 7d7…      ┆ 7d7…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
# Export the parsed, structurally typed boundary transaction tables into external storage files
for name, tx in boundary_transactions.items():
    output_path = f"{name}_boundary_transactions.csv"
    tx.write_csv(output_path)
    print("Saved:", output_path, "rows:", tx.height)

Saved: wash_trading_846_boundary_transactions.csv rows: 33681
Saved: phishing_390_boundary_transactions.csv rows: 65504
Saved: mixer_242_boundary_transactions.csv rows: 70569

Calculate high-fidelity network summary metrics evaluating cross-boundary intersections, user nodes behavior footprints, unique entity limits, chronological ranges, and asset transfer weights.

In [32]:
# Initialize data container array to aggregate diagnostics dictionaries for baseline comparison matrix construction
boundary_diagnostics_rows = []

# Process subgraphs metrics comprehensively to build structural profiles
for name, tx in boundary_transactions.items():
    nodes_df = community_nodes[name]
    
    # Isolate known ground-truth fraudulent address hashes inside optimized unique target hash lists
    fraud_nodes = set(
        nodes_df
        .filter(pl.col("label") == "fraud")
        .select("address")
        .to_series()
        .to_list()
    )
    
    # Isolate baseline non-fraud normal address hashes inside unique target hash lists
    normal_nodes = set(
        nodes_df
        .filter(pl.col("label") == "normal")
        .select("address")
        .to_series()
        .to_list()
    )
    
    # Map out the comprehensive population reference boundaries for the targeted cluster block
    community_addresses = set(
        nodes_df
        .select("address")
        .to_series()
        .to_list()
    )
    
    # Check if any boundary interactions were successfully discovered in the processing timeline
    if tx.height > 0:
        # Extract unique participating identities found in either sending or receiving roles inside this subgraph
        tx_sources = set(tx.select("source").to_series().to_list())
        tx_targets = set(tx.select("target").to_series().to_list())
        tx_nodes = tx_sources.union(tx_targets)
        
        # Compute absolute transaction totals across each localized flow classification category
        internal_count = tx.filter(pl.col("boundary_type") == "internal").height
        incoming_count = tx.filter(pl.col("boundary_type") == "incoming").height
        outgoing_count = tx.filter(pl.col("boundary_type") == "outgoing").height
        
        # Apply set operations to differentiate between internal community vertices and external entities
        community_nodes_in_tx = tx_nodes.intersection(community_addresses)
        external_nodes_in_tx = tx_nodes.difference(community_addresses)
        
        # Populate comprehensive diagnostic descriptors parsing exact topological details
        row = {
            "community_name": name,
            "n_nodes_in_community": nodes_df.height,
            "n_fraud_nodes_in_community": len(fraud_nodes),
            "n_normal_nodes_in_community": len(normal_nodes),
            "n_boundary_transactions": tx.height,
            "n_internal_transactions": internal_count,
            "n_incoming_transactions": incoming_count,
            "n_outgoing_transactions": outgoing_count,
            "n_unique_sources": len(tx_sources),
            "n_unique_targets": len(tx_targets),
            "n_all_nodes_in_boundary_tx": len(tx_nodes),
            "n_community_nodes_in_boundary_tx": len(community_nodes_in_tx),
            "n_external_nodes_in_boundary_tx": len(external_nodes_in_tx),
            "n_fraud_nodes_in_boundary_tx": len(community_nodes_in_tx.intersection(fraud_nodes)),
            "n_normal_community_nodes_in_boundary_tx": len(community_nodes_in_tx.intersection(normal_nodes)),
            "min_timestamp": tx.select(pl.col("timestamp").min()).item(),
            "max_timestamp": tx.select(pl.col("timestamp").max()).item(),
            "total_value_eth": tx.select(pl.col("value_eth").sum()).item(),
            "mean_value_eth": tx.select(pl.col("value_eth").mean()).item()
        }
    else:
        # Assign standardized empty fallback records to handle zero activity exceptions gracefully
        row = {
            "community_name": name,
            "n_nodes_in_community": nodes_df.height,
            "n_fraud_nodes_in_community": len(fraud_nodes),
            "n_normal_nodes_in_community": len(normal_nodes),
            "n_boundary_transactions": 0,
            "n_internal_transactions": 0,
            "n_incoming_transactions": 0,
            "n_outgoing_transactions": 0,
            "n_unique_sources": 0,
            "n_unique_targets": 0,
            "n_all_nodes_in_boundary_tx": 0,
            "n_community_nodes_in_boundary_tx": 0,
            "n_external_nodes_in_boundary_tx": 0,
            "n_fraud_nodes_in_boundary_tx": 0,
            "n_normal_community_nodes_in_boundary_tx": 0,
            "min_timestamp": None,
            "max_timestamp": None,
            "total_value_eth": 0,
            "mean_value_eth": None
        }
    
    # Append the calculated metrics mapping dictionary row into the main tracker list array
    boundary_diagnostics_rows.append(row)

# Transform the accumulated row metrics dictionaries list into an operational diagnostic summary DataFrame
boundary_diagnostics_df = pl.DataFrame(boundary_diagnostics_rows)
boundary_diagnostics_df

shape: (3, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ community ┆ n_nodes_i ┆ n_fraud_n ┆ n_normal_ ┆ … ┆ min_times ┆ max_times ┆ total_val ┆ mean_val │
│ _name     ┆ n_communi ┆ odes_in_c ┆ nodes_in_ ┆   ┆ tamp      ┆ tamp      ┆ ue_eth    ┆ ue_eth   │
│ ---       ┆ ty        ┆ ommunity  ┆ community ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ f64       ┆ f64      │
│           ┆ i64       ┆ i64       ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ wash_trad ┆ 2820      ┆ 459       ┆ 2361      ┆ … ┆ 176254802 ┆ 176279366 ┆ 20824.774 ┆ 0.618294 │
│ ing_846   ┆           ┆           ┆           ┆   ┆ 3         ┆ 3         ┆ 555       ┆          │
│ phishing_ ┆ 17500     ┆ 46        ┆ 17454     ┆ … ┆ 176254691 ┆ 176279366 ┆ 5169.0630 ┆ 0.078912 │
│ 390       ┆           ┆           ┆           ┆   ┆ 9         ┆ 3         ┆ 01        ┆          │
│ mixer_242 ┆ 5901      ┆ 28        ┆ 5873      ┆ … ┆ 176254691 ┆ 176279367 ┆ 693496.52 ┆ 9.827212 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆ 5         ┆ 6301      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 6. Base Transaction Feature Extraction

In [33]:
def compute_boundary_node_features(boundary_transactions, community_nodes):
    all_features = []

    # Iterate over each target network cluster block to perform localized graph metrics aggregation
    for name, tx in boundary_transactions.items():
        # Retrieve the baseline community member node metadata tracking registry frame
        nodes_df = community_nodes[name]

        # Isolate edges that are completely self-contained within the localized community cluster bounds
        internal_tx = tx.filter(
            (pl.col("source_inside_community") == True) &
            (pl.col("target_inside_community") == True)
        )

        # Isolate incoming external supply lines running from outside nodes into internal cluster targets
        incoming_external_tx = tx.filter(
            (pl.col("source_inside_community") == False) &
            (pl.col("target_inside_community") == True)
        )

        # Isolate outgoing external drain lines running from internal cluster sources to outside targets
        outgoing_external_tx = tx.filter(
            (pl.col("source_inside_community") == True) &
            (pl.col("target_inside_community") == False)
        )

        # Aggregate internal outbound metrics grouping explicitly by the internal sender address node role
        internal_out = (
            internal_tx
            .group_by("source")
            .agg([
                pl.len().alias("internal_out_tx"),
                pl.col("value_eth").sum().alias("internal_out_value_eth"),
                pl.col("target").n_unique().alias("unique_internal_receivers")
            ])
            .rename({"source": "address"})
        )

        # Aggregate internal inbound metrics grouping explicitly by the internal receiver address node role
        internal_in = (
            internal_tx
            .group_by("target")
            .agg([
                pl.len().alias("internal_in_tx"),
                pl.col("value_eth").sum().alias("internal_in_value_eth"),
                pl.col("source").n_unique().alias("unique_internal_senders")
            ])
            .rename({"target": "address"})
        )

        # Aggregate external inlet flows grouping by the internal recipient target address node role
        incoming_external = (
            incoming_external_tx
            .group_by("target")
            .agg([
                pl.len().alias("incoming_from_external_tx"),
                pl.col("value_eth").sum().alias("incoming_from_external_value_eth"),
                pl.col("source").n_unique().alias("unique_external_senders")
            ])
            .rename({"target": "address"})
        )

        # Aggregate external outlet drains grouping by the internal originator source address node role
        outgoing_external = (
            outgoing_external_tx
            .group_by("source")
            .agg([
                pl.len().alias("outgoing_to_external_tx"),
                pl.col("value_eth").sum().alias("outgoing_to_external_value_eth"),
                pl.col("target").n_unique().alias("unique_external_receivers")
            ])
            .rename({"source": "address"})
        )

        # Compile and enrich the full node topology registry with the engineered local features matrix
        features = (
            nodes_df
            .join(internal_out, on="address", how="left")
            .join(internal_in, on="address", how="left")
            .join(incoming_external, on="address", how="left")
            .join(outgoing_external, on="address", how="left")
            .fill_null(0)
            .with_columns([
                pl.lit(name).alias("community"),

# Compute cumulative localized interaction frequencies on the boundary layout
                (
                    pl.col("internal_out_tx") +
                    pl.col("internal_in_tx") +
                    pl.col("incoming_from_external_tx") +
                    pl.col("outgoing_to_external_tx")
                ).alias("total_tx_boundary"),
# Compute cumulative localized financial asset volume turnovers in Ether
                (
                    pl.col("internal_out_value_eth") +
                    pl.col("internal_in_value_eth") +
                    pl.col("incoming_from_external_value_eth") +
                    pl.col("outgoing_to_external_value_eth")
                ).alias("total_value_eth_boundary"),
# Aggregate unique directional outbound destination endpoints counters
                (
                    pl.col("unique_internal_receivers") +
                    pl.col("unique_external_receivers")
                ).alias("unique_receivers_total"),
# Aggregate unique directional inbound source origin endpoints counters
                (
                    pl.col("unique_internal_senders") +
                    pl.col("unique_external_senders")
                ).alias("unique_senders_total"),

# Compute overall structural interaction degree across internal and external components
                (
                    pl.col("unique_internal_receivers") +
                    pl.col("unique_external_receivers") +
                    pl.col("unique_internal_senders") +
                    pl.col("unique_external_senders")
                ).alias("unique_counterparties_sum")
            ])
            .select([
                "community",
                "address",
                "label",
                "internal_out_tx",
                "internal_out_value_eth",
                "unique_internal_receivers",
                "internal_in_tx",
                "internal_in_value_eth",
                "unique_internal_senders",
                "incoming_from_external_tx",
                "incoming_from_external_value_eth",
                "unique_external_senders",
                "outgoing_to_external_tx",
                "outgoing_to_external_value_eth",
                "unique_external_receivers",
                "total_tx_boundary",
                "total_value_eth_boundary",
                "unique_receivers_total",
                "unique_senders_total",
                "unique_counterparties_sum"
            ])
        )

        # Store the current community's finalized structural features array into global collections list
        all_features.append(features)

        # Output operational verification summaries displaying the dimensions of the generated table
        print("=" * 80)
        print(name)
        print("features shape:", features.shape)
        display(features.head(10))
# Concat all community features matrices vertically into a single unified analytical dataframe
    nodes_communities = (
        pl.concat(all_features)
        .sort(["community", "total_tx_boundary"], descending=[False, True])
    )

    return nodes_communities

In [34]:
# Run the pipeline function to build the complete localized graph feature table
nodes_communities = compute_boundary_node_features(
    boundary_transactions,
    community_nodes
)

nodes_communities

================================================================================
wash_trading_846
features shape: (2820, 20)

shape: (10, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ community  ┆ address    ┆ label  ┆ internal_ ┆ … ┆ total_val ┆ unique_re ┆ unique_se ┆ unique_co │
│ ---        ┆ ---        ┆ ---    ┆ out_tx    ┆   ┆ ue_eth_bo ┆ ceivers_t ┆ nders_tot ┆ unterpart │
│ str        ┆ str        ┆ str    ┆ ---       ┆   ┆ undary    ┆ otal      ┆ al        ┆ ies_sum   │
│            ┆            ┆        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆ f64       ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ wash_tradi ┆ 0x003ac1f9 ┆ normal ┆ 1         ┆ … ┆ 0.43003   ┆ 1         ┆ 1         ┆ 2         │
│ ng_846     ┆ 0ee1a46b07 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 186ce9ceac ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x0062d65b ┆ normal ┆ 8         ┆ … ┆ 9.08435   ┆ 4         ┆ 4         ┆ 8         │
│ ng_846     ┆ 5f9b850d18 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 338f697301 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x0062dbf8 ┆ normal ┆ 1         ┆ … ┆ 1.0000e-9 ┆ 1         ┆ 0         ┆ 1         │
│ ng_846     ┆ caa4d65655 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 548a2e3564 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x006bbdd3 ┆ fraud  ┆ 33        ┆ … ┆ 63.843203 ┆ 17        ┆ 22        ┆ 39        │
│ ng_846     ┆ f45ddca912 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ d570e5aee8 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x006bc22f ┆ normal ┆ 3         ┆ … ┆ 3.0000e-9 ┆ 2         ┆ 0         ┆ 2         │
│ ng_846     ┆ 03973a6632 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ df73cc6bec ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x00ae468f ┆ normal ┆ 1         ┆ … ┆ 1.0000e-9 ┆ 1         ┆ 0         ┆ 1         │
│ ng_846     ┆ 1bd31c9353 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 5c9644302b ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x00ae4e53 ┆ normal ┆ 10        ┆ … ┆ 14.387275 ┆ 6         ┆ 6         ┆ 12        │
│ ng_846     ┆ 707ae92c3f ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 470929bc45 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x00c21045 ┆ normal ┆ 7         ┆ … ┆ 6.243702  ┆ 4         ┆ 2         ┆ 6         │
│ ng_846     ┆ 59e2ce0921 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 288ee3c99a ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x00d1e64a ┆ normal ┆ 3         ┆ … ┆ 3.025934  ┆ 4         ┆ 1         ┆ 5         │
│ ng_846     ┆ 898b1c03e5 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 4e82bd23cc ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x00dc7a4e ┆ normal ┆ 1         ┆ … ┆ 1.0000e-9 ┆ 1         ┆ 0         ┆ 1         │
│ ng_846     ┆ 5b4323cf93 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ e563e9480e ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

================================================================================
phishing_390
features shape: (17500, 20)

shape: (10, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ community  ┆ address    ┆ label  ┆ internal_ ┆ … ┆ total_val ┆ unique_re ┆ unique_se ┆ unique_co │
│ ---        ┆ ---        ┆ ---    ┆ out_tx    ┆   ┆ ue_eth_bo ┆ ceivers_t ┆ nders_tot ┆ unterpart │
│ str        ┆ str        ┆ str    ┆ ---       ┆   ┆ undary    ┆ otal      ┆ al        ┆ ies_sum   │
│            ┆            ┆        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆ f64       ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ phishing_3 ┆ 0x000bf425 ┆ normal ┆ 1         ┆ … ┆ 0.000323  ┆ 2         ┆ 1         ┆ 3         │
│ 90         ┆ 4dbaf6acb4 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 809ec1511a ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x000d55e4 ┆ normal ┆ 1         ┆ … ┆ 0.000296  ┆ 2         ┆ 1         ┆ 3         │
│ 90         ┆ bbb6b8cdff ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 19ef2dec1a ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x000da24b ┆ normal ┆ 2         ┆ … ┆ 0.00423   ┆ 2         ┆ 1         ┆ 3         │
│ 90         ┆ da94cc1c59 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ e7b339ab06 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x00136a2e ┆ normal ┆ 2         ┆ … ┆ 0.001432  ┆ 2         ┆ 1         ┆ 3         │
│ 90         ┆ 22f8ed17b9 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ a15e800572 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x0014539b ┆ normal ┆ 1         ┆ … ┆ 0.000659  ┆ 2         ┆ 1         ┆ 3         │
│ 90         ┆ 3bcd161e60 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ f2086b04af ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x0015050f ┆ normal ┆ 1         ┆ … ┆ 0.00053   ┆ 2         ┆ 1         ┆ 3         │
│ 90         ┆ 65858bc4de ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 26d111c1b9 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x00176218 ┆ normal ┆ 0         ┆ … ┆ 0.015773  ┆ 0         ┆ 1         ┆ 1         │
│ 90         ┆ 70362696c4 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 84f205960f ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x00195f52 ┆ normal ┆ 1         ┆ … ┆ 0.011937  ┆ 1         ┆ 1         ┆ 2         │
│ 90         ┆ 1852d0cf84 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 8a39645a73 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x0023c0ef ┆ normal ┆ 1         ┆ … ┆ 0.006549  ┆ 2         ┆ 0         ┆ 2         │
│ 90         ┆ d0d4fd3422 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 36bfea2a7b ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ phishing_3 ┆ 0x0027e6b5 ┆ normal ┆ 1         ┆ … ┆ 0.032445  ┆ 1         ┆ 0         ┆ 1         │
│ 90         ┆ f96cb6ff3d ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 61982d1024 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

================================================================================
mixer_242
features shape: (5901, 20)

shape: (10, 20)
┌───────────┬────────────┬────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ community ┆ address    ┆ label  ┆ internal_o ┆ … ┆ total_val ┆ unique_re ┆ unique_se ┆ unique_co │
│ ---       ┆ ---        ┆ ---    ┆ ut_tx      ┆   ┆ ue_eth_bo ┆ ceivers_t ┆ nders_tot ┆ unterpart │
│ str       ┆ str        ┆ str    ┆ ---        ┆   ┆ undary    ┆ otal      ┆ al        ┆ ies_sum   │
│           ┆            ┆        ┆ u32        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆            ┆        ┆            ┆   ┆ f64       ┆ u32       ┆ u32       ┆ u32       │
╞═══════════╪════════════╪════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mixer_242 ┆ 0x00024b0c ┆ normal ┆ 1          ┆ … ┆ 0.893114  ┆ 1         ┆ 1         ┆ 2         │
│           ┆ fb6c7ae684 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ 08c32e1513 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x001a4c49 ┆ normal ┆ 0          ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│           ┆ 04ada7acbe ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ f177b80859 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x0044fb6b ┆ normal ┆ 0          ┆ … ┆ 0.002198  ┆ 1         ┆ 1         ┆ 2         │
│           ┆ 14bc24d45d ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ c82f10913e ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x00474678 ┆ normal ┆ 0          ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│           ┆ 499082d85c ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ 07d4b5b07c ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x0058cdc8 ┆ normal ┆ 0          ┆ … ┆ 0.002875  ┆ 4         ┆ 1         ┆ 5         │
│           ┆ ba2dfa609d ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ 266110d202 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x006df427 ┆ normal ┆ 2          ┆ … ┆ 914.07897 ┆ 1         ┆ 1         ┆ 2         │
│           ┆ 22a3573e26 ┆        ┆            ┆   ┆ 1         ┆           ┆           ┆           │
│           ┆ a584e587d1 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x007155d9 ┆ normal ┆ 0          ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│           ┆ b9dac297b2 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ 81413f430c ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x009fbd14 ┆ normal ┆ 0          ┆ … ┆ 0.0018    ┆ 0         ┆ 1         ┆ 1         │
│           ┆ f4129c12b0 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ cc96400967 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x00a4aef2 ┆ normal ┆ 0          ┆ … ┆ 0.024631  ┆ 0         ┆ 1         ┆ 1         │
│           ┆ b82dc4b6ea ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ 84431a55b0 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│ mixer_242 ┆ 0x00a4f382 ┆ normal ┆ 0          ┆ … ┆ 0.010522  ┆ 2         ┆ 1         ┆ 3         │
│           ┆ 3bd05d61ba ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ f52c0f0ff1 ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
│           ┆ …          ┆        ┆            ┆   ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (26_221, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ community  ┆ address    ┆ label  ┆ internal_ ┆ … ┆ total_val ┆ unique_re ┆ unique_se ┆ unique_co │
│ ---        ┆ ---        ┆ ---    ┆ out_tx    ┆   ┆ ue_eth_bo ┆ ceivers_t ┆ nders_tot ┆ unterpart │
│ str        ┆ str        ┆ str    ┆ ---       ┆   ┆ undary    ┆ otal      ┆ al        ┆ ies_sum   │
│            ┆            ┆        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆ f64       ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mixer_242  ┆ 0x28c6c062 ┆ fraud  ┆ 13362     ┆ … ┆ 520706.56 ┆ 4905      ┆ 3059      ┆ 7964      │
│            ┆ 98d514db08 ┆        ┆           ┆   ┆ 9469      ┆           ┆           ┆           │
│            ┆ 9934071355 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ mixer_242  ┆ 0xdfd5293d ┆ normal ┆ 186       ┆ … ┆ 111789.15 ┆ 4777      ┆ 2         ┆ 4779      │
│            ┆ 8e347dfe59 ┆        ┆           ┆   ┆ 6638      ┆           ┆           ┆           │
│            ┆ e90efd55b2 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ mixer_242  ┆ 0xee7ae85f ┆ normal ┆ 0         ┆ … ┆ 0.000475  ┆ 0         ┆ 3         ┆ 3         │
│            ┆ 2fe2239e27 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ d9c1e23fff ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ mixer_242  ┆ 0x699ee12a ┆ normal ┆ 0         ┆ … ┆ 636.07368 ┆ 3         ┆ 2         ┆ 5         │
│            ┆ 1d97437a4a ┆        ┆           ┆   ┆ 8         ┆           ┆           ┆           │
│            ┆ 1e87c71e5d ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ mixer_242  ┆ 0x07ae8551 ┆ normal ┆ 4         ┆ … ┆ 1122.6479 ┆ 15        ┆ 2         ┆ 17        │
│            ┆ be970cb1cc ┆        ┆           ┆   ┆ 12        ┆           ┆           ┆           │
│            ┆ a11dd7a11f ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …      ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ wash_tradi ┆ 0x8cbdc87d ┆ normal ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ ng_846     ┆ 6d98b9eab8 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 2271efade8 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0xe47762a3 ┆ normal ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ ng_846     ┆ 7f31a0b46d ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 694f6e2716 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0xd910f996 ┆ normal ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ ng_846     ┆ 86f6b26dec ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 76c34a910b ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0xba198f5b ┆ normal ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ ng_846     ┆ 780376acb0 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ 52cbb7adef ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ wash_tradi ┆ 0x884cd2f2 ┆ normal ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ ng_846     ┆ ad66191df0 ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ b4e7cd59cc ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆ …          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [35]:
nodes_communities.write_csv("nodes_communities_base_features.csv")

## 7. Temporal Motif Counting Functions

In [36]:
delta = 3600

communities = [
    "wash_trading_846",
    "phishing_390",
    "mixer_242"
]

### 7.1 Repeated Same Direction Motif

In [37]:
def count_repeated_pairs_in_group(group, delta=3600):
    # Enforce chronological ordering within the specific source-target dyad group
    group = group.sort("timestamp")

    # Extract columns to native Python primitive lists for fast pointer iteration
    timestamps = group["timestamp"].to_list()
    values = group["value_eth"].to_list()

    # Initialize two-pointer sliding window track metrics and accumulation states
    left = 0
    pair_count = 0
    motif_value_sum = 0.0
    window_value_sum = 0.0

    # Expand the right pointer to ingest the chronological transaction stream
    for right in range(len(timestamps)):
        current_time = timestamps[right]
        current_value = values[right]

        # Shrink window from the left to evict records exceeding the temporal delta
        while current_time - timestamps[left] > delta:
            window_value_sum -= values[left] # Subtract evicted asset weight from current window buffer
            left += 1

        # Calculate the number of valid lookback events currently in scope
        previous_count = right - left

        # Accumulate combinatorial counts and historical value pairings
        pair_count += previous_count
        motif_value_sum += window_value_sum + previous_count * current_value

        # Advance current transaction size into the rolling lookback buffer
        window_value_sum += current_value

    # Pack aggregated link characteristics into a single operational Polars row dataframe
    return pl.DataFrame({
        "source": [group["source"][0]],
        "target": [group["target"][0]],
        "repeat_same_direction_pair_count_1h": [pair_count],
        "repeat_same_direction_pair_value_eth_1h": [motif_value_sum]
    })

In [38]:
def compute_repeated_same_direction(
    community,
    tx,
    nodes_communities,
    delta=3600
):
    print("=" * 80)
    print(f"Processing: {community}")

    # Standardize field types, select core tracking features, and optimize sort layout
    tx = (
        tx
        .with_columns([
            pl.col("source").cast(pl.Utf8),
            pl.col("target").cast(pl.Utf8),
            pl.col("timestamp").cast(pl.Int64),
            pl.col("value_eth").cast(pl.Float64)
        ])
        .select(["source", "target", "timestamp", "value_eth"])
        .sort(["source", "target", "timestamp"])
    )

    # Isolate baseline node mappings belonging to the current community evaluation frame
    base = nodes_communities.filter(pl.col("community") == community)

    print(f"Boundary transactions: {tx.height:,}")
    print(f"Base community nodes: {base.height:,}")

    # Map groups using the sliding-window function over each individual sender-receiver dyad
    dyad_features = (
        tx
        .group_by("source", "target")
        .map_groups(lambda group: count_repeated_pairs_in_group(group, delta=delta))
        .filter(pl.col("repeat_same_direction_pair_count_1h") > 0)
    )

    print(f"Dyads with repeated same-direction motifs: {dyad_features.height:,}")

    if dyad_features.height > 0:
        print(
            "Total repeated same-direction pairs:",
            dyad_features["repeat_same_direction_pair_count_1h"].sum()
        )
    else:
        print("Total repeated same-direction pairs: 0")

    # Aggregate counts and economic values for nodes acting as directional loop origin senders
    sender_features = (
        dyad_features
        .group_by("source")
        .agg([
            pl.col("repeat_same_direction_pair_count_1h")
            .sum()
            .alias("repeat_same_direction_as_sender_count_1h"),

            pl.col("repeat_same_direction_pair_value_eth_1h")
            .sum()
            .alias("repeat_same_direction_as_sender_value_eth_1h")
        ])
        .rename({"source": "address"})
    )

    # Aggregate counts and economic values for nodes acting as directional loop target receivers
    receiver_features = (
        dyad_features
        .group_by("target")
        .agg([
            pl.col("repeat_same_direction_pair_count_1h")
            .sum()
            .alias("repeat_same_direction_as_receiver_count_1h"),

            pl.col("repeat_same_direction_pair_value_eth_1h")
            .sum()
            .alias("repeat_same_direction_as_receiver_value_eth_1h")
        ])
        .rename({"target": "address"})
    )

    # Compile all structural features back to the community layout, imputing zero for missing states
    node_features = (
        base
        .select(["community", "address", "label", "total_tx_boundary"])
        .join(sender_features, on="address", how="left")
        .join(receiver_features, on="address", how="left")
        .with_columns([
            pl.col("repeat_same_direction_as_sender_count_1h").fill_null(0),
            pl.col("repeat_same_direction_as_sender_value_eth_1h").fill_null(0),
            pl.col("repeat_same_direction_as_receiver_count_1h").fill_null(0),
            pl.col("repeat_same_direction_as_receiver_value_eth_1h").fill_null(0)
        ])
        # Compute combined interaction frequencies and asset volume weights
        .with_columns([
            (
                pl.col("repeat_same_direction_as_sender_count_1h") +
                pl.col("repeat_same_direction_as_receiver_count_1h")
            ).alias("repeat_same_direction_total_count_1h"),

            (
                pl.col("repeat_same_direction_as_sender_value_eth_1h") +
                pl.col("repeat_same_direction_as_receiver_value_eth_1h")
            ).alias("repeat_same_direction_total_value_eth_1h")
        ])
        # Calculate localized behavior densities normalized against total activity limits
        .with_columns([
            pl.when(pl.col("total_tx_boundary") > 0)
            .then(pl.col("repeat_same_direction_total_count_1h") / pl.col("total_tx_boundary"))
            .otherwise(0)
            .alias("repeat_same_direction_per_tx_1h")
        ])
    )

    # Generate high-level tracking diagnostics comparing normal vs. fraud behavioral classes
    summary = (
        node_features
        .group_by("label")
        .agg([
            pl.len().alias("n_nodes"),

            (pl.col("repeat_same_direction_total_count_1h") > 0)
            .sum()
            .alias("active_repeat_nodes"),

            (
                (pl.col("repeat_same_direction_total_count_1h") > 0).sum() / pl.len()
            ).alias("active_repeat_share"),

            pl.col("repeat_same_direction_total_count_1h").mean().alias("mean_repeat_total_count_1h"),
            pl.col("repeat_same_direction_total_count_1h").median().alias("median_repeat_total_count_1h"),
            pl.col("repeat_same_direction_total_count_1h").max().alias("max_repeat_total_count_1h"),

            pl.col("repeat_same_direction_as_sender_count_1h").mean().alias("mean_repeat_as_sender_1h"),
            pl.col("repeat_same_direction_as_receiver_count_1h").mean().alias("mean_repeat_as_receiver_1h"),

            pl.col("repeat_same_direction_per_tx_1h").mean().alias("mean_repeat_per_tx_1h"),
            pl.col("repeat_same_direction_per_tx_1h").median().alias("median_repeat_per_tx_1h"),

            pl.col("repeat_same_direction_total_value_eth_1h").mean().alias("mean_repeat_value_eth_1h"),
            pl.col("repeat_same_direction_total_value_eth_1h").median().alias("median_repeat_value_eth_1h")
        ])
        .with_columns(pl.lit(community).alias("community"))
        .select([
            "community",
            "label",
            "n_nodes",
            "active_repeat_nodes",
            "active_repeat_share",
            "mean_repeat_total_count_1h",
            "median_repeat_total_count_1h",
            "max_repeat_total_count_1h",
            "mean_repeat_as_sender_1h",
            "mean_repeat_as_receiver_1h",
            "mean_repeat_per_tx_1h",
            "median_repeat_per_tx_1h",
            "mean_repeat_value_eth_1h",
            "median_repeat_value_eth_1h"
        ])
        .sort("label")
    )

    return node_features, summary

### 7.2 Reciprocity Motif

In [39]:
def compute_reciprocity_for_community(
    community,
    tx,
    nodes_communities,
    delta=3600
):
    print("=" * 80)
    print(f"Processing reciprocity: {community}")

    # Standardize types, retain core tracking dimensions, and pre-sort by directional coordinates
    tx = (
        tx
        .with_columns([
            pl.col("hash").cast(pl.Utf8),
            pl.col("source").cast(pl.Utf8),
            pl.col("target").cast(pl.Utf8),
            pl.col("timestamp").cast(pl.Int64),
            pl.col("value_eth").cast(pl.Float64)
        ])
        .select(["hash", "source", "target", "timestamp", "value_eth"])
        .sort(["source", "target", "timestamp"])
    )

    # Isolate reference node metadata belonging explicitly to the current target community
    base = nodes_communities.filter(pl.col("community") == community)

    print(f"Boundary transactions: {tx.height:,}")
    print(f"Base community nodes: {base.height:,}")

    # Create an alias instance of the ledger representing the initial triggering transactions (A → B)
    tx_first = tx.select([
        pl.col("hash").alias("hash_1"),
        pl.col("source").alias("source_1"),
        pl.col("target").alias("target_1"),
        pl.col("timestamp").alias("timestamp_1"),
        pl.col("value_eth").alias("value_eth_1")
    ])

    # Create an alias instance of the ledger representing the returning response transactions (B → A)
    tx_second = tx.select([
        pl.col("hash").alias("hash_2"),
        pl.col("source").alias("source_2"),
        pl.col("target").alias("target_2"),
        pl.col("timestamp").alias("timestamp_2"),
        pl.col("value_eth").alias("value_eth_2")
    ])

    # Intersect self-joined streams where the sender-receiver coordinates are explicitly flipped (A → B and B → A)
    reciprocity_pairs = (
        tx_first
        .join(
            tx_second,
            left_on=["source_1", "target_1"],
            right_on=["target_2", "source_2"],
            how="inner"
        )
        # Apply filters to enforce chronological ordering and the strict temporal window delta constraint
        .filter(
            (pl.col("timestamp_2") > pl.col("timestamp_1")) &
            ((pl.col("timestamp_2") - pl.col("timestamp_1")) <= delta)
        )
        # Extract the precise duration latency gap and calculate combined transaction volumes
        .with_columns([
            (pl.col("timestamp_2") - pl.col("timestamp_1")).alias("delta_seconds"),
            (pl.col("value_eth_1") + pl.col("value_eth_2")).alias("motif_value_eth")
        ])
    )

    print(f"Reciprocity pairs: {reciprocity_pairs.height:,}")

    # Aggregate occurrence counts and value distributions for nodes acting as the initial trigger sender
    first_sender_features = (
        reciprocity_pairs
        .group_by("source_1")
        .agg([
            pl.len().alias("reciprocity_as_first_sender_count_1h"),
            pl.col("motif_value_eth").sum().alias("reciprocity_as_first_sender_value_eth_1h")
        ])
        .rename({"source_1": "address"})
    )

    # Aggregate occurrence counts and value distributions for nodes acting as the initial trigger receiver
    first_receiver_features = (
        reciprocity_pairs
        .group_by("target_1")
        .agg([
            pl.len().alias("reciprocity_as_first_receiver_count_1h"),
            pl.col("motif_value_eth").sum().alias("reciprocity_as_first_receiver_value_eth_1h")
        ])
        .rename({"target_1": "address"})
    )

    # Map the generated dyadic features back into the central node layout, safely fill missing entries with 0
    node_features = (
        base
        .select(["community", "address", "label", "total_tx_boundary"])
        .join(first_sender_features, on="address", how="left")
        .join(first_receiver_features, on="address", how="left")
        .with_columns([
            pl.col("reciprocity_as_first_sender_count_1h").fill_null(0),
            pl.col("reciprocity_as_first_sender_value_eth_1h").fill_null(0),
            pl.col("reciprocity_as_first_receiver_count_1h").fill_null(0),
            pl.col("reciprocity_as_first_receiver_value_eth_1h").fill_null(0)
        ])
        # Compute multi-role combined statistics across individual account addresses
        .with_columns([
            (
                pl.col("reciprocity_as_first_sender_count_1h") +
                pl.col("reciprocity_as_first_receiver_count_1h")
            ).alias("reciprocity_total_count_1h"),

            (
                pl.col("reciprocity_as_first_sender_value_eth_1h") +
                pl.col("reciprocity_as_first_receiver_value_eth_1h")
            ).alias("reciprocity_total_value_eth_1h")
        ])
        # Derive structural footprint metrics normalized by the aggregate boundary transaction volumes
        .with_columns([
            pl.when(pl.col("total_tx_boundary") > 0)
            .then(pl.col("reciprocity_total_count_1h") / pl.col("total_tx_boundary"))
            .otherwise(0)
            .alias("reciprocity_per_tx_1h")
        ])
    )

    # Compute descriptive statistical diagnostics to contrast normal vs. fraud populations
    summary = (
        node_features
        .group_by("label")
        .agg([
            pl.len().alias("n_nodes"),

            (pl.col("reciprocity_total_count_1h") > 0)
            .sum()
            .alias("active_reciprocity_nodes"),

            (
                (pl.col("reciprocity_total_count_1h") > 0).sum() / pl.len()
            ).alias("active_reciprocity_share"),

            pl.col("reciprocity_total_count_1h").mean().alias("mean_reciprocity_total_count_1h"),
            pl.col("reciprocity_total_count_1h").median().alias("median_reciprocity_total_count_1h"),
            pl.col("reciprocity_total_count_1h").max().alias("max_reciprocity_total_count_1h"),

            pl.col("reciprocity_as_first_sender_count_1h").mean().alias("mean_reciprocity_as_first_sender_1h"),
            pl.col("reciprocity_as_first_receiver_count_1h").mean().alias("mean_reciprocity_as_first_receiver_1h"),

            pl.col("reciprocity_per_tx_1h").mean().alias("mean_reciprocity_per_tx_1h"),
            pl.col("reciprocity_per_tx_1h").median().alias("median_reciprocity_per_tx_1h"),

            pl.col("reciprocity_total_value_eth_1h").mean().alias("mean_reciprocity_value_eth_1h"),
            pl.col("reciprocity_total_value_eth_1h").median().alias("median_reciprocity_value_eth_1h")
        ])
        .with_columns(pl.lit(community).alias("community"))
        .select([
            # Structural coordinates mapping index
            "community",
            "label",
            "n_nodes",
            # Behavior footprint coverage dimensions
            "active_reciprocity_nodes",
            "active_reciprocity_share",
            # Total frequency distribution descriptors
            "mean_reciprocity_total_count_1h",
            "median_reciprocity_total_count_1h",
            "max_reciprocity_total_count_1h",
            # Directional trigger-role profiles
            "mean_reciprocity_as_first_sender_1h",
            "mean_reciprocity_as_first_receiver_1h",
            # Density metrics normalized against transaction frequency
            "mean_reciprocity_per_tx_1h",
            "median_reciprocity_per_tx_1h",
            # Financial economic weight distributions
            "mean_reciprocity_value_eth_1h",
            "median_reciprocity_value_eth_1h"
        ])
        .sort("label")
    )

    return node_features, summary

### 7.3 Chain Motif

In [40]:
def empty_chain_contribs():
    # Return an empty schema-aligned DataFrame fallback for groups with no motif interactions
    return pl.DataFrame({
        "address": pl.Series([], dtype=pl.Utf8),
        "chain_as_start_count_1h": pl.Series([], dtype=pl.Int64),
        "chain_as_start_value_eth_1h": pl.Series([], dtype=pl.Float64),
        "chain_as_middle_count_1h": pl.Series([], dtype=pl.Int64),
        "chain_as_middle_value_eth_1h": pl.Series([], dtype=pl.Float64),
        "chain_as_end_count_1h": pl.Series([], dtype=pl.Int64),
        "chain_as_end_value_eth_1h": pl.Series([], dtype=pl.Float64)
    })


def count_chain_contribs_for_middle(group, delta=3600):
    # Establish the focal pivot node (B) from the current grouped interaction state
    middle = group["middle"][0]

    # Split and chronologically sort incoming edges (A → B)
    incoming = (
        group
        .filter(pl.col("direction") == "incoming")
        .sort("timestamp")
    )

    # Split and chronologically sort outgoing edges (B → C)
    outgoing = (
        group
        .filter(pl.col("direction") == "outgoing")
        .sort("timestamp")
    )

    # Fast-path exit if a valid chain pattern is structurally impossible
    if incoming.height == 0 or outgoing.height == 0:
        return empty_chain_contribs()

    # Cast incoming arrays to native lists for optimized index pointer lookups
    in_sources = incoming["counterparty"].to_list()
    in_times = incoming["timestamp"].to_list()
    in_values = incoming["value_eth"].to_list()

    # Cast outgoing arrays to native lists for optimized index pointer lookups
    out_targets = outgoing["counterparty"].to_list()
    out_times = outgoing["timestamp"].to_list()
    out_values = outgoing["value_eth"].to_list()

    # Map structure: address -> [start_count, start_val, middle_count, middle_val, end_count, end_val]
    contrib = defaultdict(lambda: [0, 0.0, 0, 0.0, 0, 0.0])

    # Scan each incoming event to detect subsequent casual outgoing paths
    for i in range(len(in_times)):
        a = in_sources[i]
        t_in = in_times[i]
        v_in = in_values[i]

        # Use binary search to isolate the lookback slice within the timestamp constraint
        left = bisect_right(out_times, t_in)
        right = bisect_right(out_times, t_in + delta)

        # Match with valid outgoing targets (C) inside the active window
        for j in range(left, right):
            c = out_targets[j]

            # Reject cycles and self-loops to preserve strict 3-node graph chain logic
            if a == middle or middle == c or a == c:
                continue

            v_out = out_values[j]
            motif_value = v_in + v_out

            # Log execution metrics tracking node role positioning weights
            contrib[a][0] += 1
            contrib[a][1] += motif_value

            contrib[middle][2] += 1
            contrib[middle][3] += motif_value

            contrib[c][4] += 1
            contrib[c][5] += motif_value

    if len(contrib) == 0:
        return empty_chain_contribs()

    # Convert hashmap storage records to list structure format
    rows = []
    for address, values in contrib.items():
        rows.append((
            address,
            values[0],
            values[1],
            values[2],
            values[3],
            values[4],
            values[5]
        ))

    # Re-wrap structured metrics inside an explicitly typed Polars dataframe
    return pl.DataFrame(
        rows,
        schema=[
            "address",
            "chain_as_start_count_1h",
            "chain_as_start_value_eth_1h",
            "chain_as_middle_count_1h",
            "chain_as_middle_value_eth_1h",
            "chain_as_end_count_1h",
            "chain_as_end_value_eth_1h"
        ],
        orient="row"
    )

In [41]:
def compute_chain_for_community(
    community,
    tx,
    nodes_communities,
    delta=3600
):
    print("=" * 80)
    print(f"Processing chain: {community}")

    # Standardize data types and clean self-loops from raw boundary entries
    tx = (
        tx
        .with_columns([
            pl.col("source").cast(pl.Utf8),
            pl.col("target").cast(pl.Utf8),
            pl.col("timestamp").cast(pl.Int64),
            pl.col("value_eth").cast(pl.Float64)
        ])
        .select(["source", "target", "timestamp", "value_eth"])
        .filter(pl.col("source") != pl.col("target"))
    )

    # Isolate relevant subset nodes from global tracking mappings
    base = nodes_communities.filter(pl.col("community") == community)

    print(f"Boundary transactions: {tx.height:,}")
    print(f"Base community nodes: {base.height:,}")

    # Format incoming transaction records relative to target receiver nodes
    incoming_events = (
        tx
        .select([
            pl.col("target").alias("middle"),
            pl.col("source").alias("counterparty"),
            pl.col("timestamp"),
            pl.col("value_eth")
        ])
        .with_columns(pl.lit("incoming").alias("direction"))
    )

    # Format outgoing transaction records relative to source originator nodes
    outgoing_events = (
        tx
        .select([
            pl.col("source").alias("middle"),
            pl.col("target").alias("counterparty"),
            pl.col("timestamp"),
            pl.col("value_eth")
        ])
        .with_columns(pl.lit("outgoing").alias("direction"))
    )

    # Merge events and execute custom group matching routine around the pivot nodes
    events = pl.concat([incoming_events, outgoing_events])

    chain_contribs_raw = (
        events
        .group_by("middle")
        .map_groups(lambda group: count_chain_contribs_for_middle(group, delta=delta))
    )

    # Consolidate role attributes across multi-group network outputs
    if chain_contribs_raw.height == 0:
        chain_features = empty_chain_contribs()
    else:
        chain_features = (
            chain_contribs_raw
            .group_by("address")
            .agg([
                pl.col("chain_as_start_count_1h").sum(),
                pl.col("chain_as_start_value_eth_1h").sum(),
                pl.col("chain_as_middle_count_1h").sum(),
                pl.col("chain_as_middle_value_eth_1h").sum(),
                pl.col("chain_as_end_count_1h").sum(),
                pl.col("chain_as_end_value_eth_1h").sum()
            ])
        )

    print(f"Nodes participating in chain motifs: {chain_features.height:,}")

    # Build master features schema layout, computing role counts and volume densities
    node_features = (
        base
        .select(["community", "address", "label", "total_tx_boundary"])
        .join(chain_features, on="address", how="left")
        .with_columns([
            pl.col("chain_as_start_count_1h").fill_null(0),
            pl.col("chain_as_start_value_eth_1h").fill_null(0),
            pl.col("chain_as_middle_count_1h").fill_null(0),
            pl.col("chain_as_middle_value_eth_1h").fill_null(0),
            pl.col("chain_as_end_count_1h").fill_null(0),
            pl.col("chain_as_end_value_eth_1h").fill_null(0)
        ])
        .with_columns([
            (
                pl.col("chain_as_start_count_1h") +
                pl.col("chain_as_middle_count_1h") +
                pl.col("chain_as_end_count_1h")
            ).alias("chain_total_count_1h"),

            (
                pl.col("chain_as_start_value_eth_1h") +
                pl.col("chain_as_middle_value_eth_1h") +
                pl.col("chain_as_end_value_eth_1h")
            ).alias("chain_total_value_eth_1h")
        ])
        .with_columns([
            pl.when(pl.col("total_tx_boundary") > 0)
            .then(pl.col("chain_total_count_1h") / pl.col("total_tx_boundary"))
            .otherwise(0)
            .alias("chain_per_tx_1h")
        ])
    )

    # Extract behavioral category statistics comparing normal vs. fraudulent entities
    summary = (
        node_features
        .group_by("label")
        .agg([
            pl.len().alias("n_nodes"),

            (pl.col("chain_total_count_1h") > 0)
            .sum()
            .alias("active_chain_nodes"),

            ((pl.col("chain_total_count_1h") > 0).sum() / pl.len())
            .alias("active_chain_share"),

            pl.col("chain_total_count_1h").mean().alias("mean_chain_total_count_1h"),
            pl.col("chain_total_count_1h").median().alias("median_chain_total_count_1h"),
            pl.col("chain_total_count_1h").max().alias("max_chain_total_count_1h"),

            pl.col("chain_as_start_count_1h").mean().alias("mean_chain_as_start_1h"),
            pl.col("chain_as_middle_count_1h").mean().alias("mean_chain_as_middle_1h"),
            pl.col("chain_as_end_count_1h").mean().alias("mean_chain_as_end_1h"),

            pl.col("chain_per_tx_1h").mean().alias("mean_chain_per_tx_1h"),
            pl.col("chain_per_tx_1h").median().alias("median_chain_per_tx_1h"),

            pl.col("chain_total_value_eth_1h").mean().alias("mean_chain_value_eth_1h"),
            pl.col("chain_total_value_eth_1h").median().alias("median_chain_value_eth_1h")
        ])
        .with_columns(pl.lit(community).alias("community"))
        .select([
            "community",
            "label",
            "n_nodes",
            "active_chain_nodes",
            "active_chain_share",
            "mean_chain_total_count_1h",
            "median_chain_total_count_1h",
            "max_chain_total_count_1h",
            "mean_chain_as_start_1h",
            "mean_chain_as_middle_1h",
            "mean_chain_as_end_1h",
            "mean_chain_per_tx_1h",
            "median_chain_per_tx_1h",
            "mean_chain_value_eth_1h",
            "median_chain_value_eth_1h"
        ])
        .sort("label")
    )

    print(f"Rows: {node_features.height:,}")
    print(f"Columns: {len(node_features.columns):,}")

    return node_features, summary

### 7.4 Fan-In Motif

In [42]:
def empty_fan_in_contribs():
    # Return an empty schema-aligned DataFrame fallback for groups with no fan-in motif components
    return pl.DataFrame({
        "address": pl.Series([], dtype=pl.Utf8),
        "fan_in_as_sender_count_1h": pl.Series([], dtype=pl.Int64),
        "fan_in_as_sender_value_eth_1h": pl.Series([], dtype=pl.Float64),
        "fan_in_as_center_count_1h": pl.Series([], dtype=pl.Int64),
        "fan_in_as_center_value_eth_1h": pl.Series([], dtype=pl.Float64)
    })


def count_fan_in_contribs_for_center(group, delta=3600):
    # Order transactions sequentially by timeline timestamps within the focal receiver group
    group = group.sort("timestamp")

    # Isolate the target consolidation endpoint center (C) and parse features to native arrays
    center = group["target"][0]
    sources = group["source"].to_list()
    times = group["timestamp"].to_list()
    values = group["value_eth"].to_list()

    # Map tracking structure: address -> [sender_count, sender_value, center_count, center_value]
    contrib = defaultdict(lambda: [0, 0.0, 0, 0.0])

    # Initialize two-pointer parameters alongside separate state trace trackers for each unique sender source
    left = 0
    window_count = 0
    window_value_sum = 0.0
    source_counts = defaultdict(int)
    source_value_sums = defaultdict(float)

    # Expand the sliding window pointer rightward across the timeline array
    for right in range(len(times)):
        current_time = times[right]
        current_source = sources[right]
        current_value = values[right]

        # Shift the left window boundary pointer forward to drop outdated historical events
        while current_time - times[left] > delta:
            old_source = sources[left]
            old_value = values[left]

            # Evict metrics parameters from both global sliding structures and source maps
            window_count -= 1
            window_value_sum -= old_value
            source_counts[old_source] -= 1
            source_value_sums[old_source] -= old_value

            # Clean memory registries for inactive sources with no active links left
            if source_counts[old_source] == 0:
                del source_counts[old_source]
                del source_value_sums[old_source]

            left += 1

        # Extract transaction trace frequencies and volumes belonging specifically to the current source
        same_source_count = source_counts.get(current_source, 0)
        same_source_value_sum = source_value_sums.get(current_source, 0.0)

        # Isolate valid non-identical peer interactions to satisfy distinct 3-node fan-in topology
        valid_previous_count = window_count - same_source_count
        valid_previous_value_sum = window_value_sum - same_source_value_sum

        # Aggregate parameters if a valid fan-in structure exists in the current lookback slice
        if valid_previous_count > 0:
            current_sender_value = valid_previous_value_sum + valid_previous_count * current_value

            # Update structural profiles for the incoming transaction originator address role
            contrib[current_source][0] += valid_previous_count
            contrib[current_source][1] += current_sender_value

            # Update structural profiles for the central focal target destination address role
            contrib[center][2] += valid_previous_count
            contrib[center][3] += current_sender_value

            # Back-propagate motif values onto all separate valid peer sources within the sliding layout
            for previous_source, previous_count in source_counts.items():
                if previous_source == current_source:
                    continue

                previous_value_sum = source_value_sums[previous_source]
                previous_sender_value = previous_value_sum + previous_count * current_value

                contrib[previous_source][0] += previous_count
                contrib[previous_source][1] += previous_sender_value

        # Insert current data parameters into running sliding window status buffers
        window_count += 1
        window_value_sum += current_value
        source_counts[current_source] += 1
        source_value_sums[current_source] += current_value

    if len(contrib) == 0:
        return empty_fan_in_contribs()

    # Reformat metrics dictionary arrays into a list of tracking tuples
    rows = []
    for address, values_list in contrib.items():
        rows.append((
            address,
            values_list[0],
            values_list[1],
            values_list[2],
            values_list[3]
        ))

    # Commit processed profiles back to a structured schema-aligned Polars DataFrame
    return pl.DataFrame(
        rows,
        schema=[
            "address",
            "fan_in_as_sender_count_1h",
            "fan_in_as_sender_value_eth_1h",
            "fan_in_as_center_count_1h",
            "fan_in_as_center_value_eth_1h"
        ],
        orient="row"
    )

In [43]:
def compute_fan_in_for_community(
    community,
    tx,
    nodes_communities,
    delta=3600
):
    print("=" * 80)
    print(f"Processing fan-in: {community}")

    # Standardize explicit fields, filter self-loops, and perform sorting optimized for aggregation targets
    tx = (
        tx
        .with_columns([
            pl.col("source").cast(pl.Utf8),
            pl.col("target").cast(pl.Utf8),
            pl.col("timestamp").cast(pl.Int64),
            pl.col("value_eth").cast(pl.Float64)
        ])
        .select(["source", "target", "timestamp", "value_eth"])
        .filter(pl.col("source") != pl.col("target"))
        .sort(["target", "timestamp"])
    )

    # Isolate relevant baseline structural identities mapping to the current target cluster
    base = nodes_communities.filter(pl.col("community") == community)

    print(f"Boundary transactions: {tx.height:,}")
    print(f"Base community nodes: {base.height:,}")

    # Map groups using the sliding-window function over each targeted destination sink node (center)
    fan_in_contribs_raw = (
        tx
        .group_by("target")
        .map_groups(lambda group: count_fan_in_contribs_for_center(group, delta=delta))
    )

    # Condense multi-role outputs into a standardized unique address feature list
    if fan_in_contribs_raw.height == 0:
        fan_in_features = empty_fan_in_contribs()
    else:
        fan_in_features = (
            fan_in_contribs_raw
            .group_by("address")
            .agg([
                pl.col("fan_in_as_sender_count_1h").sum(),
                pl.col("fan_in_as_sender_value_eth_1h").sum(),
                pl.col("fan_in_as_center_count_1h").sum(),
                pl.col("fan_in_as_center_value_eth_1h").sum()
            ])
        )

    print(f"Nodes participating in fan-in motifs: {fan_in_features.height:,}")

    # Align generated temporal arrays with baseline node profiles and fill unmapped elements with zero
    node_features = (
        base
        .select(["community", "address", "label", "total_tx_boundary"])
        .join(fan_in_features, on="address", how="left")
        .with_columns([
            pl.col("fan_in_as_sender_count_1h").fill_null(0),
            pl.col("fan_in_as_sender_value_eth_1h").fill_null(0),
            pl.col("fan_in_as_center_count_1h").fill_null(0),
            pl.col("fan_in_as_center_value_eth_1h").fill_null(0)
        ])
        # Compute combined frequency and asset metrics across distinct network role designations
        .with_columns([
            (
                pl.col("fan_in_as_sender_count_1h") +
                pl.col("fan_in_as_center_count_1h")
            ).alias("fan_in_total_count_1h"),

            (
                pl.col("fan_in_as_sender_value_eth_1h") +
                pl.col("fan_in_as_center_value_eth_1h")
            ).alias("fan_in_total_value_eth_1h")
        ])
        # Calculate dynamic footprint metrics normalized against entire localized boundary dimensions
        .with_columns([
            pl.when(pl.col("total_tx_boundary") > 0)
            .then(pl.col("fan_in_total_count_1h") / pl.col("total_tx_boundary"))
            .otherwise(0)
            .alias("fan_in_per_tx_1h")
        ])
    )

    # Compute high-level tracking diagnostics comparing normal vs. fraud behavioral classes
    summary = (
        node_features
        .group_by("label")
        .agg([
            pl.len().alias("n_nodes"),

            (pl.col("fan_in_total_count_1h") > 0)
            .sum()
            .alias("active_fan_in_nodes"),

            ((pl.col("fan_in_total_count_1h") > 0).sum() / pl.len())
            .alias("active_fan_in_share"),

            pl.col("fan_in_total_count_1h").mean().alias("mean_fan_in_total_count_1h"),
            pl.col("fan_in_total_count_1h").median().alias("median_fan_in_total_count_1h"),
            pl.col("fan_in_total_count_1h").max().alias("max_fan_in_total_count_1h"),

            pl.col("fan_in_as_sender_count_1h").mean().alias("mean_fan_in_as_sender_1h"),
            pl.col("fan_in_as_center_count_1h").mean().alias("mean_fan_in_as_center_1h"),

            pl.col("fan_in_per_tx_1h").mean().alias("mean_fan_in_per_tx_1h"),
            pl.col("fan_in_per_tx_1h").median().alias("median_fan_in_per_tx_1h"),

            pl.col("fan_in_total_value_eth_1h").mean().alias("mean_fan_in_value_eth_1h"),
            pl.col("fan_in_total_value_eth_1h").median().alias("median_fan_in_value_eth_1h")
        ])
        .with_columns(pl.lit(community).alias("community"))
        .select([
            # Structural coordinate mappings index
            "community",
            "label",
            "n_nodes",
            # Behavior pattern footprint coverage dimensions
            "active_fan_in_nodes",
            "active_fan_in_share",
            # Total frequency distribution descriptors
            "mean_fan_in_total_count_1h",
            "median_fan_in_total_count_1h",
            "max_fan_in_total_count_1h",
            # Role position profiles inside fan-in patterns
            "mean_fan_in_as_sender_1h",
            "mean_fan_in_as_center_1h",
            # Density variables normalized against execution rates
            "mean_fan_in_per_tx_1h",
            "median_fan_in_per_tx_1h",
            # Financial asset allocation concentrations
            "mean_fan_in_value_eth_1h",
            "median_fan_in_value_eth_1h"
        ])
        .sort("label")
    )

    print(f"Rows: {node_features.height:,}")
    print(f"Columns: {len(node_features.columns):,}")

    return node_features, summary

### 7.5 Fan-Out Motif

In [44]:
def empty_fan_out_contribs():
    # Return an empty schema-aligned DataFrame fallback for groups with no fan-out motif components
    return pl.DataFrame({
        "address": pl.Series([], dtype=pl.Utf8),
        "fan_out_as_center_count_1h": pl.Series([], dtype=pl.Int64),
        "fan_out_as_center_value_eth_1h": pl.Series([], dtype=pl.Float64),
        "fan_out_as_receiver_count_1h": pl.Series([], dtype=pl.Int64),
        "fan_out_as_receiver_value_eth_1h": pl.Series([], dtype=pl.Float64)
    })


def count_fan_out_contribs_for_center(group, delta=3600):
    # Order transactions sequentially by timeline timestamps within the focal sender group
    group = group.sort("timestamp")

    # Isolate the source originator endpoint center (A) and parse features to native arrays
    center = group["source"][0]
    targets = group["target"].to_list()
    times = group["timestamp"].to_list()
    values = group["value_eth"].to_list()

    # Map tracking structure: address -> [center_count, center_value, receiver_count, receiver_value]
    contrib = defaultdict(lambda: [0, 0.0, 0, 0.0])

    # Initialize two-pointer parameters alongside separate state trace trackers for each unique target receiver
    left = 0
    window_count = 0
    window_value_sum = 0.0
    target_counts = defaultdict(int)
    target_value_sums = defaultdict(float)

    # Expand the sliding window pointer rightward across the timeline array
    for right in range(len(times)):
        current_time = times[right]
        current_target = targets[right]
        current_value = values[right]

        # Shift the left window boundary pointer forward to drop outdated historical events
        while current_time - times[left] > delta:
            old_target = targets[left]
            old_value = values[left]

            # Evict metrics parameters from both global sliding structures and target maps
            window_count -= 1
            window_value_sum -= old_value
            target_counts[old_target] -= 1
            target_value_sums[old_target] -= old_value

            # Clean memory registries for inactive targets with no active links left
            if target_counts[old_target] == 0:
                del target_counts[old_target]
                del target_value_sums[old_target]

            left += 1

        # Extract transaction trace frequencies and volumes belonging specifically to the current target
        same_target_count = target_counts.get(current_target, 0)
        same_target_value_sum = target_value_sums.get(current_target, 0.0)

        # Isolate valid non-identical peer interactions to satisfy distinct 3-node fan-out topology
        valid_previous_count = window_count - same_target_count
        valid_previous_value_sum = window_value_sum - same_target_value_sum

        # Aggregate parameters if a valid fan-out structure exists in the current lookback slice
        if valid_previous_count > 0:
            current_receiver_value = valid_previous_value_sum + valid_previous_count * current_value

            # Update structural profiles for the central focal distributor center source address role
            contrib[center][0] += valid_previous_count
            contrib[center][1] += current_receiver_value

            # Update structural profiles for the current leaf receiver target address role
            contrib[current_target][2] += valid_previous_count
            contrib[current_target][3] += current_receiver_value

            # Back-propagate motif values onto all separate valid peer targets within the sliding layout
            for previous_target, previous_count in target_counts.items():
                if previous_target == current_target:
                    continue

                previous_value_sum = target_value_sums[previous_target]
                previous_receiver_value = previous_value_sum + previous_count * current_value

                contrib[previous_target][2] += previous_count
                contrib[previous_target][3] += previous_receiver_value

        # Insert current data parameters into running sliding window status buffers
        window_count += 1
        window_value_sum += current_value
        target_counts[current_target] += 1
        target_value_sums[current_target] += current_value

    if len(contrib) == 0:
        return empty_fan_out_contribs()

    # Reformat metrics dictionary arrays into a list of tracking tuples
    rows = []
    for address, values_list in contrib.items():
        rows.append((
            address,
            values_list[0],
            values_list[1],
            values_list[2],
            values_list[3]
        ))

    # Commit processed profiles back to a structured schema-aligned Polars DataFrame
    return pl.DataFrame(
        rows,
        schema=[
            "address",
            "fan_out_as_center_count_1h",
            "fan_out_as_center_value_eth_1h",
            "fan_out_as_receiver_count_1h",
            "fan_out_as_receiver_value_eth_1h"
        ],
        orient="row"
    )

In [45]:
def compute_fan_out_for_community(
    community,
    tx,
    nodes_communities,
    delta=3600
):
    print("=" * 80)
    print(f"Processing fan-out: {community}")

    # Standardize explicit fields, filter self-loops, and perform sorting optimized for aggregation centers
    tx = (
        tx
        .with_columns([
            pl.col("source").cast(pl.Utf8),
            pl.col("target").cast(pl.Utf8),
            pl.col("timestamp").cast(pl.Int64),
            pl.col("value_eth").cast(pl.Float64)
        ])
        .select(["source", "target", "timestamp", "value_eth"])
        .filter(pl.col("source") != pl.col("target"))
        .sort(["source", "timestamp"])
    )

    # Isolate relevant baseline structural identities mapping to the current target cluster
    base = nodes_communities.filter(pl.col("community") == community)

    print(f"Boundary transactions: {tx.height:,}")
    print(f"Base community nodes: {base.height:,}")

    # Map groups using the sliding-window function over each targeted origin source node (center)
    fan_out_contribs_raw = (
        tx
        .group_by("source")
        .map_groups(lambda group: count_fan_out_contribs_for_center(group, delta=delta))
    )

    # Condense multi-role outputs into a standardized unique address feature list
    if fan_out_contribs_raw.height == 0:
        fan_out_features = empty_fan_out_contribs()
    else:
        fan_out_features = (
            fan_out_contribs_raw
            .group_by("address")
            .agg([
                pl.col("fan_out_as_center_count_1h").sum(),
                pl.col("fan_out_as_center_value_eth_1h").sum(),
                pl.col("fan_out_as_receiver_count_1h").sum(),
                pl.col("fan_out_as_receiver_value_eth_1h").sum()
            ])
        )

    print(f"Nodes participating in fan-out motifs: {fan_out_features.height:,}")

    # Align generated temporal arrays with baseline node profiles and fill unmapped elements with zero
    node_features = (
        base
        .select(["community", "address", "label", "total_tx_boundary"])
        .join(fan_out_features, on="address", how="left")
        .with_columns([
            pl.col("fan_out_as_center_count_1h").fill_null(0),
            pl.col("fan_out_as_center_value_eth_1h").fill_null(0),
            pl.col("fan_out_as_receiver_count_1h").fill_null(0),
            pl.col("fan_out_as_receiver_value_eth_1h").fill_null(0)
        ])
        # Compute combined frequency and asset metrics across distinct network role designations
        .with_columns([
            (
                pl.col("fan_out_as_center_count_1h") +
                pl.col("fan_out_as_receiver_count_1h")
            ).alias("fan_out_total_count_1h"),

            (
                pl.col("fan_out_as_center_value_eth_1h") +
                pl.col("fan_out_as_receiver_value_eth_1h")
            ).alias("fan_out_total_value_eth_1h")
        ])
        # Calculate dynamic footprint metrics normalized against entire localized boundary dimensions
        .with_columns([
            pl.when(pl.col("total_tx_boundary") > 0)
            .then(pl.col("fan_out_total_count_1h") / pl.col("total_tx_boundary"))
            .otherwise(0)
            .alias("fan_out_per_tx_1h")
        ])
    )

    # Compute high-level tracking diagnostics comparing normal vs. fraud behavioral classes
    summary = (
        node_features
        .group_by("label")
        .agg([
            pl.len().alias("n_nodes"),

            (pl.col("fan_out_total_count_1h") > 0)
            .sum()
            .alias("active_fan_out_nodes"),

            ((pl.col("fan_out_total_count_1h") > 0).sum() / pl.len())
            .alias("active_fan_out_share"),

            pl.col("fan_out_total_count_1h").mean().alias("mean_fan_out_total_count_1h"),
            pl.col("fan_out_total_count_1h").median().alias("median_fan_out_total_count_1h"),
            pl.col("fan_out_total_count_1h").max().alias("max_fan_out_total_count_1h"),

            pl.col("fan_out_as_center_count_1h").mean().alias("mean_fan_out_as_center_1h"),
            pl.col("fan_out_as_receiver_count_1h").mean().alias("mean_fan_out_as_receiver_1h"),

            pl.col("fan_out_per_tx_1h").mean().alias("mean_fan_out_per_tx_1h"),
            pl.col("fan_out_per_tx_1h").median().alias("median_fan_out_per_tx_1h"),

            pl.col("fan_out_total_value_eth_1h").mean().alias("mean_fan_out_value_eth_1h"),
            pl.col("fan_out_total_value_eth_1h").median().alias("median_fan_out_value_eth_1h")
        ])
        .with_columns(pl.lit(community).alias("community"))
        .select([
            # Structural coordinate mappings index
            "community",
            "label",
            "n_nodes",
            # Behavior pattern footprint coverage dimensions
            "active_fan_out_nodes",
            "active_fan_out_share",
            # Total frequency distribution descriptors
            "mean_fan_out_total_count_1h",
            "median_fan_out_total_count_1h",
            "max_fan_out_total_count_1h",
            # Role position profiles inside fan-out patterns
            "mean_fan_out_as_center_1h",
            "mean_fan_out_as_receiver_1h",
            # Density variables normalized against execution rates
            "mean_fan_out_per_tx_1h",
            "median_fan_out_per_tx_1h",
            # Financial asset allocation concentrations
            "mean_fan_out_value_eth_1h",
            "median_fan_out_value_eth_1h"
        ])
        .sort("label")
    )

    print(f"Rows: {node_features.height:,}")
    print(f"Columns: {len(node_features.columns):,}")

    return node_features, summary

### 7.6 Cycle Motif

In [46]:
def empty_cycle_contribs():
    # Return an empty schema-aligned DataFrame fallback for groups with no cycle motif components
    return pl.DataFrame({
        "address": pl.Series([], dtype=pl.Utf8),
        "cycle_as_start_count_1h": pl.Series([], dtype=pl.Int64),
        "cycle_as_start_value_eth_1h": pl.Series([], dtype=pl.Float64),
        "cycle_as_middle_count_1h": pl.Series([], dtype=pl.Int64),
        "cycle_as_middle_value_eth_1h": pl.Series([], dtype=pl.Float64),
        "cycle_as_end_count_1h": pl.Series([], dtype=pl.Int64),
        "cycle_as_end_value_eth_1h": pl.Series([], dtype=pl.Float64)
    })

def build_cycle_indexes(tx):
    # Initialize index mappings for fast lookup of incoming transactions and cycle-closing pairs
    incoming_by_target = defaultdict(lambda: {"times": [], "sources": [], "values": []})
    closing_by_pair = defaultdict(lambda: {"times": [], "values": []})

    # Sort the transaction stream chronologically to ensure binary search and prefix sum compatibility
    tx_sorted = tx.sort("timestamp")

    # Populate the lookup tables with timestamps, node addresses, and transaction volumes
    for source, target, timestamp, value_eth in tx_sorted.iter_rows():
        incoming_by_target[target]["times"].append(timestamp)
        incoming_by_target[target]["sources"].append(source)
        incoming_by_target[target]["values"].append(value_eth)

        closing_by_pair[(source, target)]["times"].append(timestamp)
        closing_by_pair[(source, target)]["values"].append(value_eth)

    closing_prefix_by_pair = {}

    # Construct prefix sums over transaction values for each node pair to achieve O(1) interval value summation
    for pair, data in closing_by_pair.items():
        prefix = [0.0]
        for value in data["values"]:
            prefix.append(prefix[-1] + value)
        closing_prefix_by_pair[pair] = prefix

    return incoming_by_target, closing_by_pair, closing_prefix_by_pair

In [47]:
def compute_cycle_contribs(tx, delta=3600):
    # Build lookback index mappings and prefix value arrays for fast lookup
    incoming_by_target, closing_by_pair, closing_prefix_by_pair = build_cycle_indexes(tx)

    # Map tracking structure: address -> [start_count, start_val, middle_count, middle_val, end_count, end_val]
    contrib = defaultdict(lambda: [0, 0.0, 0, 0.0, 0, 0.0])

    tx_second_edges = tx.sort("timestamp")
    n_second_edges = tx_second_edges.height

    # Iterate over every transaction treating it as the intermediate second edge (B -> C) of the cycle
    for idx, row in enumerate(tx_second_edges.iter_rows(named=True)):
        b = row["source"]
        c = row["target"]
        t2 = row["timestamp"]
        v2 = row["value_eth"]

        incoming_data = incoming_by_target.get(b)
        if incoming_data is None:
            continue

        in_times = incoming_data["times"]
        in_sources = incoming_data["sources"]
        in_values = incoming_data["values"]

        # Identify preceding incoming edges (A -> B) that fall within the valid lookback window delta
        left_in = bisect_left(in_times, t2 - delta)
        right_in = bisect_left(in_times, t2)

        if left_in == right_in:
            continue

        # Evaluate every valid causal parent transaction candidate
        for i in range(left_in, right_in):
            a = in_sources[i]
            t1 = in_times[i]
            v1 = in_values[i]

            # Exclude self-loops and dual-node cycles to maintain strict 3-node cycle topology criteria
            if a == b or b == c or a == c:
                continue

            closing_pair = (c, a)
            closing_data = closing_by_pair.get(closing_pair)
            if closing_data is None:
                continue

            close_times = closing_data["times"]
            close_prefix = closing_prefix_by_pair[closing_pair]

            # Locate subsequent matching edges (C -> A) that close the temporal loop within the active window constraint
            left_close = bisect_right(close_times, t2)
            right_close = bisect_right(close_times, t1 + delta)

            k = right_close - left_close
            if k <= 0:
                continue

            # Calculate the total asset value transferred throughout this specific motif instance loop
            closing_value_sum = close_prefix[right_close] - close_prefix[left_close]
            motif_value_sum = k * (v1 + v2) + closing_value_sum

            # Accumulate count weights and total monetary values across all three participating node roles
            contrib[a][0] += k
            contrib[a][1] += motif_value_sum

            contrib[b][2] += k
            contrib[b][3] += motif_value_sum

            contrib[c][4] += k
            contrib[c][5] += motif_value_sum

    if len(contrib) == 0:
        return empty_cycle_contribs()

    # Reformat metrics dictionary arrays into a list of tracking tuples
    rows = []
    for address, values in contrib.items():
        rows.append((
            address,
            values[0],
            values[1],
            values[2],
            values[3],
            values[4],
            values[5]
        ))

    # Commit processed profiles back to a structured schema-aligned Polars DataFrame
    return pl.DataFrame(
        rows,
        schema=[
            "address",
            "cycle_as_start_count_1h",
            "cycle_as_start_value_eth_1h",
            "cycle_as_middle_count_1h",
            "cycle_as_middle_value_eth_1h",
            "cycle_as_end_count_1h",
            "cycle_as_end_value_eth_1h"
        ],
        orient="row"
    )

In [48]:
def compute_cycle_for_community(
    community,
    tx,
    nodes_communities,
    delta=3600
):
    print("=" * 80)
    print(f"Processing cycle: {community}")

    # Standardize data types and clean self-loops from raw boundary entries
    tx = (
        tx
        .with_columns([
            pl.col("source").cast(pl.Utf8),
            pl.col("target").cast(pl.Utf8),
            pl.col("timestamp").cast(pl.Int64),
            pl.col("value_eth").cast(pl.Float64)
        ])
        .select(["source", "target", "timestamp", "value_eth"])
        .filter(pl.col("source") != pl.col("target"))
    )

    # Isolate relevant baseline structural identities mapping to the current target cluster
    base = nodes_communities.filter(pl.col("community") == community)

    print(f"Boundary transactions: {tx.height:,}")
    print(f"Base community nodes: {base.height:,}")

    # Process localized data using the specialized cycle extraction function
    cycle_features = compute_cycle_contribs(tx, delta=delta)

    print(f"Nodes participating in cycle motifs: {cycle_features.height:,}")

    # Align generated temporal arrays with baseline node profiles and fill unmapped elements with zero
    node_features = (
        base
        .select(["community", "address", "label", "total_tx_boundary"])
        .join(cycle_features, on="address", how="left")
        .with_columns([
            pl.col("cycle_as_start_count_1h").fill_null(0),
            pl.col("cycle_as_start_value_eth_1h").fill_null(0),
            pl.col("cycle_as_middle_count_1h").fill_null(0),
            pl.col("cycle_as_middle_value_eth_1h").fill_null(0),
            pl.col("cycle_as_end_count_1h").fill_null(0),
            pl.col("cycle_as_end_value_eth_1h").fill_null(0)
        ])
        # Compute combined frequency and asset metrics across distinct network role designations
        .with_columns([
            (
                pl.col("cycle_as_start_count_1h") +
                pl.col("cycle_as_middle_count_1h") +
                pl.col("cycle_as_end_count_1h")
            ).alias("cycle_total_count_1h"),

            (
                pl.col("cycle_as_start_value_eth_1h") +
                pl.col("cycle_as_middle_value_eth_1h") +
                pl.col("cycle_as_end_value_eth_1h")
            ).alias("cycle_total_value_eth_1h")
        ])
        # Calculate dynamic footprint metrics normalized against entire localized boundary dimensions
        .with_columns([
            pl.when(pl.col("total_tx_boundary") > 0)
            .then(pl.col("cycle_total_count_1h") / pl.col("total_tx_boundary"))
            .otherwise(0)
            .alias("cycle_per_tx_1h")
        ])
    )

    # Compute descriptive statistical diagnostics to contrast normal vs. fraud populations
    summary = (
        node_features
        .group_by("label")
        .agg([
            pl.len().alias("n_nodes"),

            (pl.col("cycle_total_count_1h") > 0)
            .sum()
            .alias("active_cycle_nodes"),

            ((pl.col("cycle_total_count_1h") > 0).sum() / pl.len())
            .alias("active_cycle_share"),

            pl.col("cycle_total_count_1h").mean().alias("mean_cycle_total_count_1h"),
            pl.col("cycle_total_count_1h").median().alias("median_cycle_total_count_1h"),
            pl.col("cycle_total_count_1h").max().alias("max_cycle_total_count_1h"),

            pl.col("cycle_as_start_count_1h").mean().alias("mean_cycle_as_start_1h"),
            pl.col("cycle_as_middle_count_1h").mean().alias("mean_cycle_as_middle_1h"),
            pl.col("cycle_as_end_count_1h").mean().alias("mean_cycle_as_end_1h"),

            pl.col("cycle_per_tx_1h").mean().alias("mean_cycle_per_tx_1h"),
            pl.col("cycle_per_tx_1h").median().alias("median_cycle_per_tx_1h"),

            pl.col("cycle_total_value_eth_1h").mean().alias("mean_cycle_value_eth_1h"),
            pl.col("cycle_total_value_eth_1h").median().alias("median_cycle_value_eth_1h")
        ])
        .with_columns(pl.lit(community).alias("community"))
        .select([
            # Structural coordinates mapping index
            "community",
            "label",
            "n_nodes",
            # Behavior pattern footprint coverage dimensions
            "active_cycle_nodes",
            "active_cycle_share",
            # Total frequency distribution descriptors
            "mean_cycle_total_count_1h",
            "median_cycle_total_count_1h",
            "max_cycle_total_count_1h",
            # Role position profiles inside cycle patterns
            "mean_cycle_as_start_1h",
            "mean_cycle_as_middle_1h",
            "mean_cycle_as_end_1h",
            # Density metrics normalized against transaction frequency
            "mean_cycle_per_tx_1h",
            "median_cycle_per_tx_1h",
            # Financial economic weight distributions
            "mean_cycle_value_eth_1h",
            "median_cycle_value_eth_1h"
        ])
        .sort("label")
    )

    print(f"Rows: {node_features.height:,}")
    print(f"Columns: {len(node_features.columns):,}")

    return node_features, summary

### 7.7 Computing Motifs

In [49]:
def compute_motif_for_all_communities(
    motif_name,
    compute_function,
    feature_cols,
    communities,
    boundary_transactions,
    nodes_communities,
    delta=3600
):
    # Initialize list collectors to hold localized per-community data partitions
    all_features = []
    all_summaries = []

    print("=" * 100)
    print(f"Computing motif: {motif_name}")

    # Sequentially iterate through the partition index to isolate and process target clusters
    for community in communities:
        # Execute the motif tracking function callback passing the pre-filtered boundary transaction dictionary map
        node_features, summary = compute_function(
            community=community,
            tx=boundary_transactions[community],
            nodes_communities=nodes_communities,
            delta=delta
        )

        # Slice the core keys along with the requested configuration columns
        motif_features = node_features.select(
            ["community", "address"] + feature_cols
        )

        # Append individual outputs to the temporary list buffers
        all_features.append(motif_features)
        all_summaries.append(summary)

    # Vertically stack the array collections into centralized, multi-community master DataFrames
    features_all = pl.concat(all_features)
    summary_all = pl.concat(all_summaries)

    return features_all, summary_all

def add_motif_features_to_nodes(
    nodes_communities,
    motif_features_all,
    feature_cols
):
    # Map the processed metrics back into the master table using a multi-key left join
    nodes_communities = (
        nodes_communities
        .join(
            motif_features_all,
            on=["community", "address"],
            how="left"
        )
        # Handle unmapped structural elements by filling NaN/null entries with zero
        .with_columns([
            pl.col(col).fill_null(0)
            for col in feature_cols
        ])
    )

    return nodes_communities

## 8. Final Feature Table Creation

In [50]:
motif_configs = {
    # 2-Node Pattern: Sequential repeated transfers matching identical orientation (A → B, then A → B)
    "repeated_same_direction": {
        "compute_function": compute_repeated_same_direction,
        "feature_cols": [
            "repeat_same_direction_as_sender_count_1h",
            "repeat_same_direction_as_sender_value_eth_1h",
            "repeat_same_direction_as_receiver_count_1h",
            "repeat_same_direction_as_receiver_value_eth_1h",
            "repeat_same_direction_total_count_1h",
            "repeat_same_direction_total_value_eth_1h",
            "repeat_same_direction_per_tx_1h"
        ]
    },

    # 2-Node Pattern: Chronological bilateral exchange loop coordinates (A → B, then B → A)
    "reciprocity": {
        "compute_function": compute_reciprocity_for_community,
        "feature_cols": [
            "reciprocity_as_first_sender_count_1h",
            "reciprocity_as_first_sender_value_eth_1h",
            "reciprocity_as_first_receiver_count_1h",
            "reciprocity_as_first_receiver_value_eth_1h",
            "reciprocity_total_count_1h",
            "reciprocity_total_value_eth_1h",
            "reciprocity_per_tx_1h"
        ]
    },

    # 3-Node Pattern: Linear transactional sequence propagation channels (A → B → C)
    "chain": {
        "compute_function": compute_chain_for_community,
        "feature_cols": [
            "chain_as_start_count_1h",
            "chain_as_start_value_eth_1h",
            "chain_as_middle_count_1h",
            "chain_as_middle_value_eth_1h",
            "chain_as_end_count_1h",
            "chain_as_end_value_eth_1h",
            "chain_total_count_1h",
            "chain_total_value_eth_1h",
            "chain_per_tx_1h"
        ]
    },

    # 3-Node Pattern: Multi-source funds consolidation into a single repository center (A → C and B → C)
    "fan_in": {
        "compute_function": compute_fan_in_for_community,
        "feature_cols": [
            "fan_in_as_sender_count_1h",
            "fan_in_as_sender_value_eth_1h",
            "fan_in_as_center_count_1h",
            "fan_in_as_center_value_eth_1h",
            "fan_in_total_count_1h",
            "fan_in_total_value_eth_1h",
            "fan_in_per_tx_1h"
        ]
    },

    # 3-Node Pattern: Single-source wallet dispersal branching out to multiple leaves (A → B and A → C)
    "fan_out": {
        "compute_function": compute_fan_out_for_community,
        "feature_cols": [
            "fan_out_as_center_count_1h",
            "fan_out_as_center_value_eth_1h",
            "fan_out_as_receiver_count_1h",
            "fan_out_as_receiver_value_eth_1h",
            "fan_out_total_count_1h",
            "fan_out_total_value_eth_1h",
            "fan_out_per_tx_1h"
        ]
    },

    # 3-Node Pattern: Closed chronological circular liquidity loop system (A → B → C → A)
    "cycle": {
        "compute_function": compute_cycle_for_community,
        "feature_cols": [
            "cycle_as_start_count_1h",
            "cycle_as_start_value_eth_1h",
            "cycle_as_middle_count_1h",
            "cycle_as_middle_value_eth_1h",
            "cycle_as_end_count_1h",
            "cycle_as_end_value_eth_1h",
            "cycle_total_count_1h",
            "cycle_total_value_eth_1h",
            "cycle_per_tx_1h"
        ]
    }
}

In [51]:
# Initialize storage maps to keep standalone copies of raw results per motif type
motif_features_results = {}
motif_summary_results = {}

# Iteratively execute, aggregate, and merge metrics for every temporal motif configuration
for motif_name, config in motif_configs.items():
    # Run the core multi-community processor for the active motif pattern lookups
    features_all, summary_all = compute_motif_for_all_communities(
        motif_name=motif_name,
        compute_function=config["compute_function"],
        feature_cols=config["feature_cols"],
        communities=communities,
        boundary_transactions=boundary_transactions,
        nodes_communities=nodes_communities,
        delta=delta
    )

    # Persist intermediate structures into independent tracking dictionaries
    motif_features_results[motif_name] = features_all
    motif_summary_results[motif_name] = summary_all

    # Sequentially append the newly generated feature metrics onto the primary nodes table
    nodes_communities = add_motif_features_to_nodes(
        nodes_communities=nodes_communities,
        motif_features_all=features_all,
        feature_cols=config["feature_cols"]
    )

====================================================================================================
Computing motif: repeated_same_direction
================================================================================
Processing: wash_trading_846
Boundary transactions: 33,681
Base community nodes: 2,820
Dyads with repeated same-direction motifs: 2,331
Total repeated same-direction pairs: 28132
================================================================================
Processing: phishing_390
Boundary transactions: 65,504
Base community nodes: 17,500
Dyads with repeated same-direction motifs: 1,460
Total repeated same-direction pairs: 619931
================================================================================
Processing: mixer_242
Boundary transactions: 70,569
Base community nodes: 5,901
Dyads with repeated same-direction motifs: 1,643
Total repeated same-direction pairs: 3185282
====================================================================================================
Computing motif: reciprocity
================================================================================
Processing reciprocity: wash_trading_846
Boundary transactions: 33,681
Base community nodes: 2,820
Reciprocity pairs: 25,207
================================================================================
Processing reciprocity: phishing_390
Boundary transactions: 65,504
Base community nodes: 17,500
Reciprocity pairs: 212
================================================================================
Processing reciprocity: mixer_242
Boundary transactions: 70,569
Base community nodes: 5,901
Reciprocity pairs: 73
====================================================================================================
Computing motif: chain
================================================================================
Processing chain: wash_trading_846
Boundary transactions: 33,681
Base community nodes: 2,820
Nodes participating in chain motifs: 2,943
Rows: 2,820
Columns: 13
================================================================================
Processing chain: phishing_390
Boundary transactions: 65,500
Base community nodes: 17,500
Nodes participating in chain motifs: 19,310
Rows: 17,500
Columns: 13
================================================================================
Processing chain: mixer_242
Boundary transactions: 70,435
Base community nodes: 5,901
Nodes participating in chain motifs: 9,987
Rows: 5,901
Columns: 13
====================================================================================================
Computing motif: fan_in
================================================================================
Processing fan-in: wash_trading_846
Boundary transactions: 33,681
Base community nodes: 2,820
Nodes participating in fan-in motifs: 3,068
Rows: 2,820
Columns: 11
================================================================================
Processing fan-in: phishing_390
Boundary transactions: 65,500
Base community nodes: 17,500
Nodes participating in fan-in motifs: 16,586
Rows: 17,500
Columns: 11
================================================================================
Processing fan-in: mixer_242
Boundary transactions: 70,435
Base community nodes: 5,901
Nodes participating in fan-in motifs: 5,119
Rows: 5,901
Columns: 11
====================================================================================================
Computing motif: fan_out
================================================================================
Processing fan-out: wash_trading_846
Boundary transactions: 33,681
Base community nodes: 2,820
Nodes participating in fan-out motifs: 2,114
Rows: 2,820
Columns: 11
================================================================================
Processing fan-out: phishing_390
Boundary transactions: 65,500
Base community nodes: 17,500
Nodes participating in fan-out motifs: 13,668
Rows: 17,500
Columns: 11
================================================================================
Processing fan-out: mixer_242
Boundary transactions: 70,435
Base community nodes: 5,901
Nodes participating in fan-out motifs: 11,330
Rows: 5,901
Columns: 11
====================================================================================================
Computing motif: cycle
================================================================================
Processing cycle: wash_trading_846
Boundary transactions: 33,681
Base community nodes: 2,820
Nodes participating in cycle motifs: 119
Rows: 2,820
Columns: 13
================================================================================
Processing cycle: phishing_390
Boundary transactions: 65,500
Base community nodes: 17,500
Nodes participating in cycle motifs: 0
Rows: 17,500
Columns: 13
================================================================================
Processing cycle: mixer_242
Boundary transactions: 70,435
Base community nodes: 5,901
Nodes participating in cycle motifs: 44
Rows: 5,901
Columns: 13

In [52]:
nodes_communities.write_csv("nodes_communities_with_all_motifs.csv")

print("Saved: nodes_communities_with_all_motifs.csv")
print("Rows:", nodes_communities.height)
print("Columns:", len(nodes_communities.columns))

Saved: nodes_communities_with_all_motifs.csv
Rows: 26221
Columns: 66